[package]
name = "rezel-lang-java"
version.workspace = true
categories = ["parser-implementations"]
edition.workspace = true
include = [
	"/grammar/**",
	"/src/**",
	"/Cargo.toml",
	"/README.md",
	"/THIRD_PARTY_NOTICES.md",
	"/LICENSE-APACHE",
	"/LICENSE-MIT",
]
keywords = ["java", "parser", "syntax-tree", "cst"]
license.workspace = true
repository.workspace = true
description = "Java SE 26 parser and typed syntax for Rezel"

[features]
default = []
highlight = ["dep:rezel-highlight"]

[dependencies]
rezel-common.workspace = true
rezel-highlight = { workspace = true, optional = true }
rezel-lr.workspace = true
zerocopy.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
