[package]
name = "rezel-lang-kotlin"
version.workspace = true
authors.workspace = true
categories = ["parser-implementations"]
edition.workspace = true
homepage.workspace = true
include = [
	"/src/**",
	"/Cargo.toml",
	"/README.md",
	"/THIRD_PARTY_NOTICES.md",
	"/LICENSE-APACHE",
	"/LICENSE-MIT",
]
keywords = ["kotlin", "parser", "syntax-tree", "cst"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Kotlin 2.4 parser and typed syntax for Rezel"

[features]
default = []
highlight = ["dep:rezel-highlight"]

[dependencies]
rezel-common.workspace = true
rezel-highlight = { workspace = true, optional = true }
rezel-lr.workspace = true
unicode-ident.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
