[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "indentation"
rust_path = "crate::tokens::INDENTATION"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "newlines"
rust_path = "crate::tokens::NEWLINES"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "strings"
rust_path = "crate::tokens::STRINGS"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "pythonIdentifiers"
rust_path = "crate::identifier::TOKENIZER"

[[binding]]
kind = "context-tracker"
source = "./tokens.js"
name = "trackIndent"
rust_path = "crate::tokens::TRACK_INDENT"

[[binding]]
kind = "property-source"
source = "./highlight"
name = "pythonHighlighting"
rust_path = "crate::python_highlighting"
