//! Java SE 26 parser and typed syntax generated by Rezel.

#![forbid(unsafe_code)]
#![doc = include_str!("../README.md")]

use std::sync::{Arc, OnceLock};

use rezel_common::{NodePropSource, ParseError, ParseErrorKind, ParseRequest, PartialParse};
use rezel_lr::LRParser;

#[cfg(feature = "highlight")]
use rezel_common::{TextRange, Tree};
#[cfg(feature = "highlight")]
pub use rezel_highlight::HighlightSpan;
#[cfg(feature = "highlight")]
use rezel_highlight::TagSet;

#[rustfmt::skip]
mod generated;
mod identifier;
mod input;
mod syntax;

pub mod ast;
pub mod terms;
#[rustfmt::skip]
pub mod typed;

use input::JavaInput;

/// Java parser with JLS Unicode-escape translation.
pub type JavaParser = LRParser;

/// Return a cheap clone of the default recovering Java parser.
#[must_use]
pub fn parser() -> JavaParser {
    default_parser().clone()
}

/// Project the Java CST into Lezer-compatible syntactic highlight tags.
///
/// This deliberately performs no name binding, scope analysis, or semantic
/// classification. Downstream consumers decide how abstract tags map to
/// their own token legends.
#[cfg(feature = "highlight")]
pub fn highlight_spans(tree: &Tree, range: Option<TextRange>, put_span: impl FnMut(HighlightSpan)) {
    rezel_highlight::highlight_spans(tree, range, put_span);
}

fn default_parser() -> &'static LRParser {
    static PARSER: OnceLock<LRParser> = OnceLock::new();
    PARSER.get_or_init(|| {
        LRParser::from_language(&generated::LANGUAGE).with_create_parse(create_java_parse)
    })
}

fn create_java_parse(
    parser: &LRParser,
    request: ParseRequest,
) -> Result<Box<dyn PartialParse>, ParseError> {
    let input = JavaInput::new(Arc::clone(request.input()));
    if parser.is_strict()
        && let Some(position) = input.malformed_escape_in(request.selected_ranges())
    {
        return Err(ParseError::new(
            ParseErrorKind::Syntax,
            Some(position),
            "malformed eligible Java Unicode escape",
        ));
    }
    let request = request.map_input(|_| Arc::new(input));
    parser.create_lr_parse(&request)
}

fn java_highlighting() -> NodePropSource {
    #[cfg(feature = "highlight")]
    {
        let tags = rezel_highlight::tags();
        rezel_highlight::style_tags([
            ("null", TagSet::from(tags.null)),
            ("instanceof", TagSet::from(tags.operator_keyword)),
            ("this", TagSet::from(tags.self_)),
            ("new super assert open to with void", TagSet::from(tags.keyword)),
            (
                "class interface extends implements enum var record",
                TagSet::from(tags.definition_keyword),
            ),
            ("module package import", TagSet::from(tags.module_keyword)),
            (
                "switch while for if else case default do break continue return try catch finally throw yield when",
                TagSet::from(tags.control_keyword),
            ),
            (
                "requires exports opens uses provides public private protected static transitive abstract final strictfp synchronized native transient volatile throws sealed non permits",
                TagSet::from(tags.modifier),
            ),
            ("IntegerLiteral", TagSet::from(tags.integer)),
            ("FloatingPointLiteral", TagSet::from(tags.float)),
            ("StringLiteral TextBlock", TagSet::from(tags.string)),
            ("CharacterLiteral", TagSet::from(tags.character)),
            ("LineComment", TagSet::from(tags.line_comment)),
            ("BlockComment", TagSet::from(tags.block_comment)),
            ("BooleanLiteral", TagSet::from(tags.bool_)),
            (
                "PrimitiveType",
                TagSet::from(tags.standard.apply(tags.type_name)),
            ),
            ("TypeName", TagSet::from(tags.type_name)),
            ("Identifier", TagSet::from(tags.variable_name)),
            (
                "MethodName/Identifier",
                TagSet::from(tags.function.apply(tags.variable_name)),
            ),
            (
                "Definition",
                TagSet::from(tags.definition.apply(tags.variable_name)),
            ),
            ("ArithOp", TagSet::from(tags.arithmetic_operator)),
            ("LogicOp", TagSet::from(tags.logic_operator)),
            ("BitOp", TagSet::from(tags.bitwise_operator)),
            ("CompareOp", TagSet::from(tags.compare_operator)),
            ("AssignOp", TagSet::from(tags.definition_operator)),
            ("UpdateOp", TagSet::from(tags.update_operator)),
            ("Asterisk", TagSet::from(tags.punctuation)),
            ("Label", TagSet::from(tags.label_name)),
            ("( )", TagSet::from(tags.paren)),
            ("[ ]", TagSet::from(tags.square_bracket)),
            ("{ }", TagSet::from(tags.brace)),
            (".", TagSet::from(tags.deref_operator)),
            (", ;", TagSet::from(tags.separator)),
            (
                "_",
                TagSet::from(tags.special.apply(tags.variable_name)),
            ),
        ])
        .expect("Java highlight selectors are valid")
    }
    #[cfg(not(feature = "highlight"))]
    {
        rezel_common::group_prop().source(|_| None)
    }
}
