// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:swift:update
#![allow(clippy::all, clippy::pedantic, missing_docs)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SwiftKind {
    Error,
    TypeKeyword,
    ProtocolKeyword,
    Identifier,
    AttributeName,
    AttributeNameWithArguments,
    Term13,
    SourceLocation,
    RegexLiteral,
    StringLiteral,
    Term17,
    Term18,
    Term19,
    LineComment,
    BlockComment,
    SourceFile,
    Shebang,
    CodeBlockItem,
    OperatorDeclaration,
    Prefix,
    Infix,
    Postfix,
    Operator,
    OperatorName,
    Term31,
    Term32,
    Term33,
    Term34,
    Term35,
    Term36,
    Term37,
    Term38,
    Term39,
    Term40,
    Term41,
    Term42,
    Term43,
    Term44,
    Equal,
    Arrow,
    Term50,
    OperatorPrecedenceAndTypes,
    Colon,
    PrecedenceGroupName,
    SelfKeyword,
    CapitalSelfKeyword,
    Comma,
    OperatorDesignatedType,
    RightBrace,
    PrecedenceGroupDeclaration,
    Precedencegroup,
    LeftBrace,
    PrecedenceGroupAssociativity,
    Associativity,
    Left,
    Right,
    None,
    PrecedenceGroupAssignment,
    Assignment,
    BooleanLiteral,
    PrecedenceGroupRelation,
    HigherThan,
    LowerThan,
    UsingDeclaration,
    Using,
    Attribute,
    Term77,
    ModuleSelector,
    DollarIdentifier,
    RightParen,
    LeftParen,
    AttributeArgumentClause,
    LabeledExpression,
    TernaryExpression,
    SequenceExpression,
    TryExpression,
    Try,
    TrySuffix,
    AwaitExpression,
    Await,
    UnsafeExpression,
    Unsafe,
    ConsumeExpression,
    Consume,
    UnderscoreMoveKeyword,
    CopyExpression,
    Copy,
    BorrowExpression,
    Borrow,
    UnderscoreBorrowKeyword,
    PackExpansionExpression,
    Repeat,
    PackElementExpression,
    Each,
    InOutExpression,
    PrefixOperatorExpression,
    PrefixOperator,
    DoExpression,
    Do,
    CodeBlock,
    CatchClause,
    Catch,
    CatchItemList,
    CatchItem,
    WhereClause,
    Where,
    KeyPathExpression,
    Backslash,
    OptionalType,
    ImplicitlyUnwrappedOptionalType,
    SuppressedType,
    MetatypeType,
    Period,
    Term137,
    Term138,
    ArrayType,
    PackExpansionType,
    AttributedType,
    SimpleTypeSpecifier,
    Inout,
    Borrowing,
    Consuming,
    Sending,
    Isolated,
    UnderscoreConstKeyword,
    DoubleUnderscoreSharedKeyword,
    DoubleUnderscoreOwnedKeyword,
    NonisolatedTypeSpecifier,
    Nonisolated,
    NonisolatedSpecifierArgument,
    Nonsending,
    LifetimeTypeSpecifier,
    DependsOn,
    Scoped,
    LifetimeSpecifierArgument,
    IntegerLiteral,
    FunctionType,
    TupleType,
    TupleTypeElement,
    TupleTypeElementLabel,
    Wildcard,
    Term166,
    FunctionEffect,
    Async,
    Throws,
    ThrowsType,
    CompositionType,
    PackElementType,
    MemberType,
    TypeIdentifierName,
    GenericArgumentClause,
    IntegerLiteralExpression,
    TupleExpression,
    SomeOrAnyType,
    Some,
    Any,
    InlineArrayType,
    Of,
    DictionaryType,
    IdentifierType,
    AnyKeyword,
    KeyPathComponent,
    KeyPathMethodComponent,
    DeclReferenceExpression,
    Init,
    DeclNameArguments,
    DeclNameArgument,
    KeyPathPropertyComponent,
    KeyPathSubscriptComponent,
    KeyPathOptionalComponent,
    DiscardAssignmentExpression,
    FunctionCallExpression,
    BasicCallSuffix,
    ArgumentClause,
    TrailingClosureClause,
    ClosureExpression,
    ClosureSignature,
    IfConfigDeclaration,
    IfConfigIfClause,
    PoundIf,
    PoundIfToken,
    IfConfigCondition,
    IfConfigConditionToken,
    FloatLiteral,
    IfConfigElseifClause,
    PoundElseif,
    PoundElseifToken,
    IfConfigElseClause,
    PoundElse,
    PoundElseToken,
    PoundEndif,
    PoundEndifToken,
    ClosureCaptureClause,
    ClosureCaptureItem,
    ClosureCaptureSpecifier,
    Weak,
    Unowned,
    ModifierDetail,
    InitializerClause,
    ParenthesizedClosureParameterClause,
    ClosureParameter,
    DeclarationModifier,
    ParameterNames,
    TypeAnnotation,
    ReturnClause,
    UnparenthesizedClosureParameterClause,
    ClosureShorthandParameter,
    In,
    AdditionalTrailingClosure,
    ArgumentLabel,
    IfExpression,
    If,
    ConditionList,
    ConditionElement,
    AvailabilityCondition,
    Available,
    Unavailable,
    AvailabilityArgument,
    AvailabilityPlatformVersion,
    AvailabilityVersion,
    AvailabilityLabeledArgument,
    Message,
    Renamed,
    Introduced,
    Obsoleted,
    Deprecated,
    UnavailableKeyword,
    Noasync,
    OptionalBindingCondition,
    Let,
    Var,
    IdentifierPattern,
    WildcardPattern,
    ValueBindingPattern,
    UnderscoreMutatingKeyword,
    UnderscoreConsumingKeyword,
    TuplePattern,
    TuplePatternElement,
    ConditionInitializerClause,
    MatchingPatternCondition,
    Case,
    SwitchCasePattern,
    UnderscoreBorrowingKeyword,
    MemberAccessExpression,
    GenericSpecializationExpression,
    SubscriptCallExpression,
    ConditionLabeledExpression,
    OptionalChainingExpression,
    ForceUnwrapExpression,
    PostfixOperatorExpression,
    ConditionArgumentClause,
    IsTypePattern,
    Is,
    PostfixIfConfigExpression,
    Semicolon,
    CastOperator,
    As,
    TypeExpression,
    BinaryOperator,
    ArrowExpression,
    Else,
    SwitchExpression,
    Switch,
    SwitchCase,
    SwitchCaseLabel,
    SwitchCaseItem,
    Default,
    SwitchCaseCodeBlockItem,
    Public,
    Package,
    Internal,
    Fileprivate,
    Private,
    Open,
    Final,
    Static,
    Class,
    Override,
    Required,
    Convenience,
    Lazy,
    Mutating,
    Nonmutating,
    Distributed,
    Indirect,
    Optional,
    Dynamic,
    DoubleUnderscoreConsumingKeyword,
    UnderscoreLocalKeyword,
    ImportDeclaration,
    Import,
    ImportKind,
    Typealias,
    Struct,
    Enum,
    Protocol,
    Func,
    ImportPath,
    ImportPathComponent,
    VariableDeclaration,
    PatternBinding,
    NamedOpaqueReturnType,
    GenericParameterClause,
    GenericParameter,
    TypeName,
    GenericWhereClause,
    GenericRequirement,
    LayoutRequirement,
    _Trivial,
    _TrivialAtMost,
    _TrivialStride,
    _UnknownLayout,
    _RefCountedObject,
    _NativeRefCountedObject,
    _Class,
    _NativeClass,
    _BridgeObject,
    PropertyBlock,
    AccessorBlock,
    AccessorDeclaration,
    Yielding,
    AccessorSpecifier,
    Get,
    Set,
    DidSet,
    WillSet,
    UnsafeAddress,
    AddressWithOwner,
    AddressWithNativeOwner,
    UnsafeMutableAddress,
    MutableAddressWithOwner,
    MutableAddressWithNativeOwner,
    ReadAccessorKeyword,
    Read,
    ModifyAccessorKeyword,
    Modify,
    Mutate,
    AccessorParameter,
    GetterCodeBlock,
    GetterCodeBlockItem,
    GetterDeclaration,
    FunctionDeclaration,
    FunctionName,
    FunctionOperatorName,
    FunctionParameterClause,
    FunctionParameter,
    DefaultArgumentClause,
    Reasync,
    Rethrows,
    StructDeclaration,
    InheritanceClause,
    InheritedType,
    ClassRestrictionType,
    MemberBlock,
    EnumCaseDeclaration,
    EnumCaseElement,
    EnumCaseParameterClause,
    EnumCaseParameter,
    RawValueClause,
    MacroExpansionDeclaration,
    Term523,
    ClassDeclaration,
    ActorDeclaration,
    Actor,
    EnumDeclaration,
    ProtocolDeclaration,
    PrimaryAssociatedTypeClause,
    TypeAliasDeclaration,
    LabeledStatement,
    ExpressionStatement,
    GuardStatement,
    Guard,
    WhileStatement,
    While,
    RepeatStatement,
    ForStatement,
    For,
    DoStatement,
    ThrowsClause,
    DeferStatement,
    Defer,
    ReturnStatement,
    Return,
    ThrowStatement,
    Throw,
    BreakStatement,
    Break,
    ContinueStatement,
    Continue,
    FallThroughStatement,
    Fallthrough,
    YieldStatement,
    Yield,
    DiscardStatement,
    Discard,
    ThenStatement,
    Then,
    ExtensionDeclaration,
    Extension,
    AssociatedTypeDeclaration,
    Associatedtype,
    DefaultType,
    MacroDeclaration,
    Macro,
    DeinitializerDeclaration,
    Deinit,
    SubscriptDeclaration,
    Subscript,
    InitializerDeclaration,
    MacroExpansionExpression,
    ImplicitMemberExpression,
    SuperExpression,
    SuperKeyword,
    FloatLiteralExpression,
    StringLiteralExpression,
    RegexLiteralExpression,
    BooleanLiteralExpression,
    NilLiteralExpression,
    Nil,
    CollectionExpression,
    CollectionElement,
    EffectsAttributeArgumentList,
    EffectsAttributeOperator,
    EffectsAttributeBackslash,
    SpecializeAttributeArgumentList,
    SpecializeTargetFunctionArgument,
    Target,
    SpecializeAvailabilityArgument,
    Availability,
    LabeledSpecializeArgument,
    Exported,
    Kind,
    Spi,
    SpiModule,
    SpecializedAttributeArgument,
    DifferentiableAttributeArguments,
    ForwardDifferentiabilityKeyword,
    Reverse,
    LinearDifferentiabilityKeyword,
    DifferentiabilityWithRespectToArgument,
    Wrt,
    DifferentiabilityArgument,
    DifferentiabilityArguments,
    DifferentiabilityArgumentList,
    DerivativeAttributeArguments,
    ABIAttributeArguments,
    AttributeArgument,
    AttributeArgumentGroup,
    AttributeBracketClause,
    AttributeBraceClause,
    AttributeArgumentKeyword,
    InvalidUsingDeclaration,
    PoundSourceLocation,
    PoundSourceLocationArguments,
    File,
    Line,
}
#[derive(Clone, Copy, Debug)]
pub enum SwiftLanguage {}
impl rezel_common::SyntaxLanguage for SwiftLanguage {
    type Kind = SwiftKind;
    fn kind(node: &rezel_common::SyntaxNode) -> Option<Self::Kind> {
        let node_type = node.node_type();
        let node_set = (crate::generated::LANGUAGE.node_set)();
        let expected = node_set.get(node_type.id())?;
        if !node_type.is(expected) {
            return None;
        }
        let kind = match node_type.id() {
            0u16 => SwiftKind::Error,
            1u16 => SwiftKind::TypeKeyword,
            2u16 => SwiftKind::ProtocolKeyword,
            3u16 => SwiftKind::Identifier,
            54u16 => SwiftKind::Identifier,
            213u16 => SwiftKind::Identifier,
            4u16 => SwiftKind::AttributeName,
            79u16 => SwiftKind::AttributeName,
            5u16 => SwiftKind::AttributeNameWithArguments,
            6u16 => SwiftKind::AttributeNameWithArguments,
            7u16 => SwiftKind::AttributeNameWithArguments,
            8u16 => SwiftKind::AttributeNameWithArguments,
            9u16 => SwiftKind::AttributeNameWithArguments,
            10u16 => SwiftKind::AttributeNameWithArguments,
            11u16 => SwiftKind::AttributeNameWithArguments,
            12u16 => SwiftKind::AttributeNameWithArguments,
            13u16 => SwiftKind::Term13,
            628u16 => SwiftKind::Term13,
            14u16 => SwiftKind::SourceLocation,
            15u16 => SwiftKind::RegexLiteral,
            16u16 => SwiftKind::StringLiteral,
            17u16 => SwiftKind::Term17,
            49u16 => SwiftKind::Term17,
            18u16 => SwiftKind::Term18,
            48u16 => SwiftKind::Term18,
            19u16 => SwiftKind::Term19,
            47u16 => SwiftKind::Term19,
            20u16 => SwiftKind::LineComment,
            21u16 => SwiftKind::BlockComment,
            22u16 => SwiftKind::SourceFile,
            23u16 => SwiftKind::Shebang,
            24u16 => SwiftKind::CodeBlockItem,
            575u16 => SwiftKind::CodeBlockItem,
            25u16 => SwiftKind::OperatorDeclaration,
            26u16 => SwiftKind::Prefix,
            27u16 => SwiftKind::Infix,
            28u16 => SwiftKind::Postfix,
            29u16 => SwiftKind::Operator,
            30u16 => SwiftKind::OperatorName,
            31u16 => SwiftKind::Term31,
            32u16 => SwiftKind::Term32,
            33u16 => SwiftKind::Term33,
            34u16 => SwiftKind::Term34,
            35u16 => SwiftKind::Term35,
            36u16 => SwiftKind::Term36,
            37u16 => SwiftKind::Term37,
            38u16 => SwiftKind::Term38,
            39u16 => SwiftKind::Term39,
            40u16 => SwiftKind::Term40,
            41u16 => SwiftKind::Term41,
            42u16 => SwiftKind::Term42,
            43u16 => SwiftKind::Term43,
            44u16 => SwiftKind::Term44,
            45u16 => SwiftKind::Equal,
            46u16 => SwiftKind::Arrow,
            50u16 => SwiftKind::Term50,
            51u16 => SwiftKind::OperatorPrecedenceAndTypes,
            52u16 => SwiftKind::Colon,
            53u16 => SwiftKind::PrecedenceGroupName,
            55u16 => SwiftKind::SelfKeyword,
            56u16 => SwiftKind::CapitalSelfKeyword,
            57u16 => SwiftKind::Comma,
            58u16 => SwiftKind::OperatorDesignatedType,
            59u16 => SwiftKind::RightBrace,
            60u16 => SwiftKind::PrecedenceGroupDeclaration,
            61u16 => SwiftKind::Precedencegroup,
            62u16 => SwiftKind::LeftBrace,
            63u16 => SwiftKind::PrecedenceGroupAssociativity,
            64u16 => SwiftKind::Associativity,
            65u16 => SwiftKind::Left,
            66u16 => SwiftKind::Right,
            67u16 => SwiftKind::None,
            68u16 => SwiftKind::PrecedenceGroupAssignment,
            69u16 => SwiftKind::Assignment,
            70u16 => SwiftKind::BooleanLiteral,
            71u16 => SwiftKind::PrecedenceGroupRelation,
            72u16 => SwiftKind::HigherThan,
            73u16 => SwiftKind::LowerThan,
            74u16 => SwiftKind::UsingDeclaration,
            75u16 => SwiftKind::Using,
            76u16 => SwiftKind::Attribute,
            77u16 => SwiftKind::Term77,
            78u16 => SwiftKind::ModuleSelector,
            80u16 => SwiftKind::DollarIdentifier,
            81u16 => SwiftKind::RightParen,
            82u16 => SwiftKind::LeftParen,
            83u16 => SwiftKind::AttributeArgumentClause,
            657u16 => SwiftKind::AttributeArgumentClause,
            84u16 => SwiftKind::LabeledExpression,
            85u16 => SwiftKind::TernaryExpression,
            118u16 => SwiftKind::TernaryExpression,
            301u16 => SwiftKind::TernaryExpression,
            367u16 => SwiftKind::TernaryExpression,
            86u16 => SwiftKind::SequenceExpression,
            119u16 => SwiftKind::SequenceExpression,
            302u16 => SwiftKind::SequenceExpression,
            368u16 => SwiftKind::SequenceExpression,
            87u16 => SwiftKind::TryExpression,
            120u16 => SwiftKind::TryExpression,
            303u16 => SwiftKind::TryExpression,
            369u16 => SwiftKind::TryExpression,
            88u16 => SwiftKind::Try,
            89u16 => SwiftKind::TrySuffix,
            90u16 => SwiftKind::AwaitExpression,
            121u16 => SwiftKind::AwaitExpression,
            304u16 => SwiftKind::AwaitExpression,
            370u16 => SwiftKind::AwaitExpression,
            91u16 => SwiftKind::Await,
            92u16 => SwiftKind::UnsafeExpression,
            122u16 => SwiftKind::UnsafeExpression,
            305u16 => SwiftKind::UnsafeExpression,
            371u16 => SwiftKind::UnsafeExpression,
            93u16 => SwiftKind::Unsafe,
            94u16 => SwiftKind::ConsumeExpression,
            123u16 => SwiftKind::ConsumeExpression,
            306u16 => SwiftKind::ConsumeExpression,
            372u16 => SwiftKind::ConsumeExpression,
            95u16 => SwiftKind::Consume,
            96u16 => SwiftKind::UnderscoreMoveKeyword,
            97u16 => SwiftKind::CopyExpression,
            124u16 => SwiftKind::CopyExpression,
            307u16 => SwiftKind::CopyExpression,
            373u16 => SwiftKind::CopyExpression,
            98u16 => SwiftKind::Copy,
            99u16 => SwiftKind::BorrowExpression,
            125u16 => SwiftKind::BorrowExpression,
            308u16 => SwiftKind::BorrowExpression,
            374u16 => SwiftKind::BorrowExpression,
            100u16 => SwiftKind::Borrow,
            101u16 => SwiftKind::UnderscoreBorrowKeyword,
            102u16 => SwiftKind::PackExpansionExpression,
            126u16 => SwiftKind::PackExpansionExpression,
            309u16 => SwiftKind::PackExpansionExpression,
            375u16 => SwiftKind::PackExpansionExpression,
            103u16 => SwiftKind::Repeat,
            104u16 => SwiftKind::PackElementExpression,
            127u16 => SwiftKind::PackElementExpression,
            310u16 => SwiftKind::PackElementExpression,
            376u16 => SwiftKind::PackElementExpression,
            105u16 => SwiftKind::Each,
            106u16 => SwiftKind::InOutExpression,
            128u16 => SwiftKind::InOutExpression,
            311u16 => SwiftKind::InOutExpression,
            377u16 => SwiftKind::InOutExpression,
            107u16 => SwiftKind::PrefixOperatorExpression,
            129u16 => SwiftKind::PrefixOperatorExpression,
            180u16 => SwiftKind::PrefixOperatorExpression,
            312u16 => SwiftKind::PrefixOperatorExpression,
            378u16 => SwiftKind::PrefixOperatorExpression,
            108u16 => SwiftKind::PrefixOperator,
            109u16 => SwiftKind::DoExpression,
            110u16 => SwiftKind::Do,
            111u16 => SwiftKind::CodeBlock,
            574u16 => SwiftKind::CodeBlock,
            112u16 => SwiftKind::CatchClause,
            113u16 => SwiftKind::Catch,
            114u16 => SwiftKind::CatchItemList,
            115u16 => SwiftKind::CatchItem,
            116u16 => SwiftKind::WhereClause,
            117u16 => SwiftKind::Where,
            130u16 => SwiftKind::KeyPathExpression,
            131u16 => SwiftKind::Backslash,
            132u16 => SwiftKind::OptionalType,
            174u16 => SwiftKind::OptionalType,
            133u16 => SwiftKind::ImplicitlyUnwrappedOptionalType,
            175u16 => SwiftKind::ImplicitlyUnwrappedOptionalType,
            134u16 => SwiftKind::SuppressedType,
            187u16 => SwiftKind::SuppressedType,
            194u16 => SwiftKind::SuppressedType,
            135u16 => SwiftKind::MetatypeType,
            182u16 => SwiftKind::MetatypeType,
            136u16 => SwiftKind::Period,
            137u16 => SwiftKind::Term137,
            138u16 => SwiftKind::Term138,
            139u16 => SwiftKind::ArrayType,
            140u16 => SwiftKind::PackExpansionType,
            141u16 => SwiftKind::AttributedType,
            142u16 => SwiftKind::SimpleTypeSpecifier,
            143u16 => SwiftKind::Inout,
            144u16 => SwiftKind::Borrowing,
            145u16 => SwiftKind::Consuming,
            146u16 => SwiftKind::Sending,
            147u16 => SwiftKind::Isolated,
            148u16 => SwiftKind::UnderscoreConstKeyword,
            149u16 => SwiftKind::DoubleUnderscoreSharedKeyword,
            150u16 => SwiftKind::DoubleUnderscoreOwnedKeyword,
            151u16 => SwiftKind::NonisolatedTypeSpecifier,
            152u16 => SwiftKind::Nonisolated,
            153u16 => SwiftKind::NonisolatedSpecifierArgument,
            154u16 => SwiftKind::Nonsending,
            155u16 => SwiftKind::LifetimeTypeSpecifier,
            156u16 => SwiftKind::DependsOn,
            157u16 => SwiftKind::Scoped,
            158u16 => SwiftKind::LifetimeSpecifierArgument,
            160u16 => SwiftKind::LifetimeSpecifierArgument,
            159u16 => SwiftKind::IntegerLiteral,
            199u16 => SwiftKind::IntegerLiteral,
            161u16 => SwiftKind::FunctionType,
            162u16 => SwiftKind::TupleType,
            163u16 => SwiftKind::TupleTypeElement,
            164u16 => SwiftKind::TupleTypeElementLabel,
            165u16 => SwiftKind::Wildcard,
            166u16 => SwiftKind::Term166,
            167u16 => SwiftKind::FunctionEffect,
            169u16 => SwiftKind::FunctionEffect,
            503u16 => SwiftKind::FunctionEffect,
            505u16 => SwiftKind::FunctionEffect,
            570u16 => SwiftKind::FunctionEffect,
            168u16 => SwiftKind::Async,
            170u16 => SwiftKind::Throws,
            171u16 => SwiftKind::ThrowsType,
            172u16 => SwiftKind::CompositionType,
            186u16 => SwiftKind::CompositionType,
            593u16 => SwiftKind::CompositionType,
            173u16 => SwiftKind::PackElementType,
            176u16 => SwiftKind::MemberType,
            177u16 => SwiftKind::TypeIdentifierName,
            192u16 => SwiftKind::TypeIdentifierName,
            178u16 => SwiftKind::GenericArgumentClause,
            179u16 => SwiftKind::IntegerLiteralExpression,
            181u16 => SwiftKind::TupleExpression,
            314u16 => SwiftKind::TupleExpression,
            379u16 => SwiftKind::TupleExpression,
            183u16 => SwiftKind::SomeOrAnyType,
            592u16 => SwiftKind::SomeOrAnyType,
            184u16 => SwiftKind::Some,
            185u16 => SwiftKind::Any,
            188u16 => SwiftKind::InlineArrayType,
            189u16 => SwiftKind::Of,
            190u16 => SwiftKind::DictionaryType,
            191u16 => SwiftKind::IdentifierType,
            195u16 => SwiftKind::IdentifierType,
            654u16 => SwiftKind::IdentifierType,
            193u16 => SwiftKind::AnyKeyword,
            196u16 => SwiftKind::KeyPathComponent,
            204u16 => SwiftKind::KeyPathComponent,
            207u16 => SwiftKind::KeyPathComponent,
            208u16 => SwiftKind::KeyPathComponent,
            197u16 => SwiftKind::KeyPathMethodComponent,
            198u16 => SwiftKind::DeclReferenceExpression,
            210u16 => SwiftKind::DeclReferenceExpression,
            212u16 => SwiftKind::DeclReferenceExpression,
            289u16 => SwiftKind::DeclReferenceExpression,
            293u16 => SwiftKind::DeclReferenceExpression,
            313u16 => SwiftKind::DeclReferenceExpression,
            586u16 => SwiftKind::DeclReferenceExpression,
            632u16 => SwiftKind::DeclReferenceExpression,
            651u16 => SwiftKind::DeclReferenceExpression,
            200u16 => SwiftKind::Init,
            201u16 => SwiftKind::DeclNameArguments,
            202u16 => SwiftKind::DeclNameArgument,
            203u16 => SwiftKind::KeyPathPropertyComponent,
            205u16 => SwiftKind::KeyPathSubscriptComponent,
            206u16 => SwiftKind::KeyPathOptionalComponent,
            209u16 => SwiftKind::DiscardAssignmentExpression,
            211u16 => SwiftKind::FunctionCallExpression,
            297u16 => SwiftKind::FunctionCallExpression,
            318u16 => SwiftKind::FunctionCallExpression,
            328u16 => SwiftKind::FunctionCallExpression,
            336u16 => SwiftKind::FunctionCallExpression,
            346u16 => SwiftKind::FunctionCallExpression,
            355u16 => SwiftKind::FunctionCallExpression,
            387u16 => SwiftKind::FunctionCallExpression,
            396u16 => SwiftKind::FunctionCallExpression,
            609u16 => SwiftKind::FunctionCallExpression,
            619u16 => SwiftKind::FunctionCallExpression,
            214u16 => SwiftKind::BasicCallSuffix,
            215u16 => SwiftKind::ArgumentClause,
            216u16 => SwiftKind::TrailingClosureClause,
            217u16 => SwiftKind::ClosureExpression,
            218u16 => SwiftKind::ClosureSignature,
            219u16 => SwiftKind::IfConfigDeclaration,
            338u16 => SwiftKind::IfConfigDeclaration,
            429u16 => SwiftKind::IfConfigDeclaration,
            492u16 => SwiftKind::IfConfigDeclaration,
            513u16 => SwiftKind::IfConfigDeclaration,
            576u16 => SwiftKind::IfConfigDeclaration,
            580u16 => SwiftKind::IfConfigDeclaration,
            220u16 => SwiftKind::IfConfigIfClause,
            339u16 => SwiftKind::IfConfigIfClause,
            430u16 => SwiftKind::IfConfigIfClause,
            493u16 => SwiftKind::IfConfigIfClause,
            514u16 => SwiftKind::IfConfigIfClause,
            577u16 => SwiftKind::IfConfigIfClause,
            581u16 => SwiftKind::IfConfigIfClause,
            221u16 => SwiftKind::PoundIf,
            222u16 => SwiftKind::PoundIfToken,
            223u16 => SwiftKind::IfConfigCondition,
            224u16 => SwiftKind::IfConfigConditionToken,
            225u16 => SwiftKind::FloatLiteral,
            226u16 => SwiftKind::IfConfigElseifClause,
            360u16 => SwiftKind::IfConfigElseifClause,
            431u16 => SwiftKind::IfConfigElseifClause,
            494u16 => SwiftKind::IfConfigElseifClause,
            515u16 => SwiftKind::IfConfigElseifClause,
            578u16 => SwiftKind::IfConfigElseifClause,
            582u16 => SwiftKind::IfConfigElseifClause,
            227u16 => SwiftKind::PoundElseif,
            228u16 => SwiftKind::PoundElseifToken,
            229u16 => SwiftKind::IfConfigElseClause,
            361u16 => SwiftKind::IfConfigElseClause,
            432u16 => SwiftKind::IfConfigElseClause,
            495u16 => SwiftKind::IfConfigElseClause,
            516u16 => SwiftKind::IfConfigElseClause,
            579u16 => SwiftKind::IfConfigElseClause,
            583u16 => SwiftKind::IfConfigElseClause,
            230u16 => SwiftKind::PoundElse,
            231u16 => SwiftKind::PoundElseToken,
            232u16 => SwiftKind::PoundEndif,
            233u16 => SwiftKind::PoundEndifToken,
            234u16 => SwiftKind::ClosureCaptureClause,
            235u16 => SwiftKind::ClosureCaptureItem,
            236u16 => SwiftKind::ClosureCaptureSpecifier,
            237u16 => SwiftKind::Weak,
            238u16 => SwiftKind::Unowned,
            239u16 => SwiftKind::ModifierDetail,
            240u16 => SwiftKind::InitializerClause,
            241u16 => SwiftKind::ParenthesizedClosureParameterClause,
            242u16 => SwiftKind::ClosureParameter,
            243u16 => SwiftKind::DeclarationModifier,
            407u16 => SwiftKind::DeclarationModifier,
            471u16 => SwiftKind::DeclarationModifier,
            244u16 => SwiftKind::ParameterNames,
            245u16 => SwiftKind::TypeAnnotation,
            451u16 => SwiftKind::TypeAnnotation,
            246u16 => SwiftKind::ReturnClause,
            507u16 => SwiftKind::ReturnClause,
            247u16 => SwiftKind::UnparenthesizedClosureParameterClause,
            248u16 => SwiftKind::ClosureShorthandParameter,
            249u16 => SwiftKind::In,
            250u16 => SwiftKind::AdditionalTrailingClosure,
            251u16 => SwiftKind::ArgumentLabel,
            252u16 => SwiftKind::IfExpression,
            253u16 => SwiftKind::If,
            254u16 => SwiftKind::ConditionList,
            255u16 => SwiftKind::ConditionElement,
            256u16 => SwiftKind::AvailabilityCondition,
            257u16 => SwiftKind::Available,
            258u16 => SwiftKind::Unavailable,
            259u16 => SwiftKind::AvailabilityArgument,
            260u16 => SwiftKind::AvailabilityPlatformVersion,
            261u16 => SwiftKind::AvailabilityVersion,
            262u16 => SwiftKind::AvailabilityLabeledArgument,
            263u16 => SwiftKind::Message,
            264u16 => SwiftKind::Renamed,
            265u16 => SwiftKind::Introduced,
            266u16 => SwiftKind::Obsoleted,
            267u16 => SwiftKind::Deprecated,
            268u16 => SwiftKind::UnavailableKeyword,
            269u16 => SwiftKind::Noasync,
            270u16 => SwiftKind::OptionalBindingCondition,
            271u16 => SwiftKind::Let,
            272u16 => SwiftKind::Var,
            273u16 => SwiftKind::IdentifierPattern,
            287u16 => SwiftKind::IdentifierPattern,
            447u16 => SwiftKind::IdentifierPattern,
            623u16 => SwiftKind::IdentifierPattern,
            274u16 => SwiftKind::WildcardPattern,
            275u16 => SwiftKind::ValueBindingPattern,
            284u16 => SwiftKind::ValueBindingPattern,
            285u16 => SwiftKind::ValueBindingPattern,
            448u16 => SwiftKind::ValueBindingPattern,
            276u16 => SwiftKind::UnderscoreMutatingKeyword,
            277u16 => SwiftKind::UnderscoreConsumingKeyword,
            278u16 => SwiftKind::TuplePattern,
            449u16 => SwiftKind::TuplePattern,
            279u16 => SwiftKind::TuplePatternElement,
            450u16 => SwiftKind::TuplePatternElement,
            280u16 => SwiftKind::ConditionInitializerClause,
            281u16 => SwiftKind::MatchingPatternCondition,
            282u16 => SwiftKind::Case,
            283u16 => SwiftKind::SwitchCasePattern,
            286u16 => SwiftKind::UnderscoreBorrowingKeyword,
            288u16 => SwiftKind::MemberAccessExpression,
            315u16 => SwiftKind::MemberAccessExpression,
            322u16 => SwiftKind::MemberAccessExpression,
            330u16 => SwiftKind::MemberAccessExpression,
            340u16 => SwiftKind::MemberAccessExpression,
            349u16 => SwiftKind::MemberAccessExpression,
            381u16 => SwiftKind::MemberAccessExpression,
            390u16 => SwiftKind::MemberAccessExpression,
            603u16 => SwiftKind::MemberAccessExpression,
            613u16 => SwiftKind::MemberAccessExpression,
            652u16 => SwiftKind::MemberAccessExpression,
            655u16 => SwiftKind::MemberAccessExpression,
            290u16 => SwiftKind::GenericSpecializationExpression,
            316u16 => SwiftKind::GenericSpecializationExpression,
            323u16 => SwiftKind::GenericSpecializationExpression,
            331u16 => SwiftKind::GenericSpecializationExpression,
            341u16 => SwiftKind::GenericSpecializationExpression,
            350u16 => SwiftKind::GenericSpecializationExpression,
            382u16 => SwiftKind::GenericSpecializationExpression,
            391u16 => SwiftKind::GenericSpecializationExpression,
            604u16 => SwiftKind::GenericSpecializationExpression,
            614u16 => SwiftKind::GenericSpecializationExpression,
            291u16 => SwiftKind::SubscriptCallExpression,
            317u16 => SwiftKind::SubscriptCallExpression,
            324u16 => SwiftKind::SubscriptCallExpression,
            332u16 => SwiftKind::SubscriptCallExpression,
            342u16 => SwiftKind::SubscriptCallExpression,
            347u16 => SwiftKind::SubscriptCallExpression,
            351u16 => SwiftKind::SubscriptCallExpression,
            356u16 => SwiftKind::SubscriptCallExpression,
            383u16 => SwiftKind::SubscriptCallExpression,
            392u16 => SwiftKind::SubscriptCallExpression,
            605u16 => SwiftKind::SubscriptCallExpression,
            615u16 => SwiftKind::SubscriptCallExpression,
            292u16 => SwiftKind::ConditionLabeledExpression,
            380u16 => SwiftKind::ConditionLabeledExpression,
            611u16 => SwiftKind::ConditionLabeledExpression,
            294u16 => SwiftKind::OptionalChainingExpression,
            319u16 => SwiftKind::OptionalChainingExpression,
            325u16 => SwiftKind::OptionalChainingExpression,
            333u16 => SwiftKind::OptionalChainingExpression,
            343u16 => SwiftKind::OptionalChainingExpression,
            352u16 => SwiftKind::OptionalChainingExpression,
            384u16 => SwiftKind::OptionalChainingExpression,
            393u16 => SwiftKind::OptionalChainingExpression,
            606u16 => SwiftKind::OptionalChainingExpression,
            616u16 => SwiftKind::OptionalChainingExpression,
            295u16 => SwiftKind::ForceUnwrapExpression,
            320u16 => SwiftKind::ForceUnwrapExpression,
            326u16 => SwiftKind::ForceUnwrapExpression,
            334u16 => SwiftKind::ForceUnwrapExpression,
            344u16 => SwiftKind::ForceUnwrapExpression,
            353u16 => SwiftKind::ForceUnwrapExpression,
            385u16 => SwiftKind::ForceUnwrapExpression,
            394u16 => SwiftKind::ForceUnwrapExpression,
            607u16 => SwiftKind::ForceUnwrapExpression,
            617u16 => SwiftKind::ForceUnwrapExpression,
            296u16 => SwiftKind::PostfixOperatorExpression,
            321u16 => SwiftKind::PostfixOperatorExpression,
            327u16 => SwiftKind::PostfixOperatorExpression,
            329u16 => SwiftKind::PostfixOperatorExpression,
            335u16 => SwiftKind::PostfixOperatorExpression,
            345u16 => SwiftKind::PostfixOperatorExpression,
            348u16 => SwiftKind::PostfixOperatorExpression,
            354u16 => SwiftKind::PostfixOperatorExpression,
            386u16 => SwiftKind::PostfixOperatorExpression,
            389u16 => SwiftKind::PostfixOperatorExpression,
            395u16 => SwiftKind::PostfixOperatorExpression,
            608u16 => SwiftKind::PostfixOperatorExpression,
            612u16 => SwiftKind::PostfixOperatorExpression,
            618u16 => SwiftKind::PostfixOperatorExpression,
            298u16 => SwiftKind::ConditionArgumentClause,
            388u16 => SwiftKind::ConditionArgumentClause,
            610u16 => SwiftKind::ConditionArgumentClause,
            299u16 => SwiftKind::IsTypePattern,
            300u16 => SwiftKind::Is,
            337u16 => SwiftKind::PostfixIfConfigExpression,
            357u16 => SwiftKind::PostfixIfConfigExpression,
            358u16 => SwiftKind::PostfixIfConfigExpression,
            397u16 => SwiftKind::PostfixIfConfigExpression,
            620u16 => SwiftKind::PostfixIfConfigExpression,
            359u16 => SwiftKind::Semicolon,
            362u16 => SwiftKind::CastOperator,
            363u16 => SwiftKind::As,
            364u16 => SwiftKind::TypeExpression,
            589u16 => SwiftKind::TypeExpression,
            590u16 => SwiftKind::TypeExpression,
            591u16 => SwiftKind::TypeExpression,
            594u16 => SwiftKind::TypeExpression,
            653u16 => SwiftKind::TypeExpression,
            365u16 => SwiftKind::BinaryOperator,
            621u16 => SwiftKind::BinaryOperator,
            366u16 => SwiftKind::ArrowExpression,
            398u16 => SwiftKind::ArrowExpression,
            622u16 => SwiftKind::ArrowExpression,
            624u16 => SwiftKind::ArrowExpression,
            399u16 => SwiftKind::Else,
            400u16 => SwiftKind::SwitchExpression,
            401u16 => SwiftKind::Switch,
            402u16 => SwiftKind::SwitchCase,
            403u16 => SwiftKind::SwitchCaseLabel,
            404u16 => SwiftKind::SwitchCaseItem,
            405u16 => SwiftKind::Default,
            406u16 => SwiftKind::SwitchCaseCodeBlockItem,
            408u16 => SwiftKind::Public,
            409u16 => SwiftKind::Package,
            410u16 => SwiftKind::Internal,
            411u16 => SwiftKind::Fileprivate,
            412u16 => SwiftKind::Private,
            413u16 => SwiftKind::Open,
            414u16 => SwiftKind::Final,
            415u16 => SwiftKind::Static,
            416u16 => SwiftKind::Class,
            417u16 => SwiftKind::Override,
            418u16 => SwiftKind::Required,
            419u16 => SwiftKind::Convenience,
            420u16 => SwiftKind::Lazy,
            421u16 => SwiftKind::Mutating,
            422u16 => SwiftKind::Nonmutating,
            423u16 => SwiftKind::Distributed,
            424u16 => SwiftKind::Indirect,
            425u16 => SwiftKind::Optional,
            426u16 => SwiftKind::Dynamic,
            427u16 => SwiftKind::DoubleUnderscoreConsumingKeyword,
            428u16 => SwiftKind::UnderscoreLocalKeyword,
            433u16 => SwiftKind::ImportDeclaration,
            434u16 => SwiftKind::Import,
            435u16 => SwiftKind::ImportKind,
            436u16 => SwiftKind::Typealias,
            437u16 => SwiftKind::Struct,
            438u16 => SwiftKind::Enum,
            439u16 => SwiftKind::Protocol,
            440u16 => SwiftKind::Func,
            441u16 => SwiftKind::ImportPath,
            444u16 => SwiftKind::ImportPath,
            442u16 => SwiftKind::ImportPathComponent,
            443u16 => SwiftKind::ImportPathComponent,
            445u16 => SwiftKind::VariableDeclaration,
            446u16 => SwiftKind::PatternBinding,
            452u16 => SwiftKind::NamedOpaqueReturnType,
            453u16 => SwiftKind::GenericParameterClause,
            454u16 => SwiftKind::GenericParameter,
            455u16 => SwiftKind::TypeName,
            456u16 => SwiftKind::GenericWhereClause,
            457u16 => SwiftKind::GenericRequirement,
            458u16 => SwiftKind::LayoutRequirement,
            459u16 => SwiftKind::_Trivial,
            460u16 => SwiftKind::_TrivialAtMost,
            461u16 => SwiftKind::_TrivialStride,
            462u16 => SwiftKind::_UnknownLayout,
            463u16 => SwiftKind::_RefCountedObject,
            464u16 => SwiftKind::_NativeRefCountedObject,
            465u16 => SwiftKind::_Class,
            466u16 => SwiftKind::_NativeClass,
            467u16 => SwiftKind::_BridgeObject,
            468u16 => SwiftKind::PropertyBlock,
            469u16 => SwiftKind::AccessorBlock,
            470u16 => SwiftKind::AccessorDeclaration,
            472u16 => SwiftKind::Yielding,
            473u16 => SwiftKind::AccessorSpecifier,
            474u16 => SwiftKind::Get,
            475u16 => SwiftKind::Set,
            476u16 => SwiftKind::DidSet,
            477u16 => SwiftKind::WillSet,
            478u16 => SwiftKind::UnsafeAddress,
            479u16 => SwiftKind::AddressWithOwner,
            480u16 => SwiftKind::AddressWithNativeOwner,
            481u16 => SwiftKind::UnsafeMutableAddress,
            482u16 => SwiftKind::MutableAddressWithOwner,
            483u16 => SwiftKind::MutableAddressWithNativeOwner,
            484u16 => SwiftKind::ReadAccessorKeyword,
            485u16 => SwiftKind::Read,
            486u16 => SwiftKind::ModifyAccessorKeyword,
            487u16 => SwiftKind::Modify,
            488u16 => SwiftKind::Mutate,
            489u16 => SwiftKind::AccessorParameter,
            490u16 => SwiftKind::GetterCodeBlock,
            491u16 => SwiftKind::GetterCodeBlockItem,
            496u16 => SwiftKind::GetterDeclaration,
            497u16 => SwiftKind::FunctionDeclaration,
            498u16 => SwiftKind::FunctionName,
            499u16 => SwiftKind::FunctionOperatorName,
            500u16 => SwiftKind::FunctionParameterClause,
            501u16 => SwiftKind::FunctionParameter,
            502u16 => SwiftKind::DefaultArgumentClause,
            504u16 => SwiftKind::Reasync,
            506u16 => SwiftKind::Rethrows,
            508u16 => SwiftKind::StructDeclaration,
            509u16 => SwiftKind::InheritanceClause,
            510u16 => SwiftKind::InheritedType,
            511u16 => SwiftKind::ClassRestrictionType,
            512u16 => SwiftKind::MemberBlock,
            517u16 => SwiftKind::EnumCaseDeclaration,
            518u16 => SwiftKind::EnumCaseElement,
            519u16 => SwiftKind::EnumCaseParameterClause,
            520u16 => SwiftKind::EnumCaseParameter,
            521u16 => SwiftKind::RawValueClause,
            522u16 => SwiftKind::MacroExpansionDeclaration,
            523u16 => SwiftKind::Term523,
            524u16 => SwiftKind::ClassDeclaration,
            525u16 => SwiftKind::ActorDeclaration,
            526u16 => SwiftKind::Actor,
            527u16 => SwiftKind::EnumDeclaration,
            528u16 => SwiftKind::ProtocolDeclaration,
            529u16 => SwiftKind::PrimaryAssociatedTypeClause,
            530u16 => SwiftKind::TypeAliasDeclaration,
            531u16 => SwiftKind::LabeledStatement,
            532u16 => SwiftKind::ExpressionStatement,
            560u16 => SwiftKind::ExpressionStatement,
            533u16 => SwiftKind::GuardStatement,
            534u16 => SwiftKind::Guard,
            535u16 => SwiftKind::WhileStatement,
            536u16 => SwiftKind::While,
            537u16 => SwiftKind::RepeatStatement,
            538u16 => SwiftKind::ForStatement,
            539u16 => SwiftKind::For,
            540u16 => SwiftKind::DoStatement,
            541u16 => SwiftKind::ThrowsClause,
            542u16 => SwiftKind::DeferStatement,
            543u16 => SwiftKind::Defer,
            544u16 => SwiftKind::ReturnStatement,
            545u16 => SwiftKind::Return,
            546u16 => SwiftKind::ThrowStatement,
            547u16 => SwiftKind::Throw,
            548u16 => SwiftKind::BreakStatement,
            549u16 => SwiftKind::Break,
            550u16 => SwiftKind::ContinueStatement,
            551u16 => SwiftKind::Continue,
            552u16 => SwiftKind::FallThroughStatement,
            553u16 => SwiftKind::Fallthrough,
            554u16 => SwiftKind::YieldStatement,
            555u16 => SwiftKind::Yield,
            556u16 => SwiftKind::DiscardStatement,
            557u16 => SwiftKind::Discard,
            558u16 => SwiftKind::ThenStatement,
            559u16 => SwiftKind::Then,
            561u16 => SwiftKind::ExtensionDeclaration,
            562u16 => SwiftKind::Extension,
            563u16 => SwiftKind::AssociatedTypeDeclaration,
            564u16 => SwiftKind::Associatedtype,
            565u16 => SwiftKind::DefaultType,
            566u16 => SwiftKind::MacroDeclaration,
            567u16 => SwiftKind::Macro,
            568u16 => SwiftKind::DeinitializerDeclaration,
            569u16 => SwiftKind::Deinit,
            571u16 => SwiftKind::SubscriptDeclaration,
            572u16 => SwiftKind::Subscript,
            573u16 => SwiftKind::InitializerDeclaration,
            584u16 => SwiftKind::MacroExpansionExpression,
            585u16 => SwiftKind::ImplicitMemberExpression,
            587u16 => SwiftKind::SuperExpression,
            588u16 => SwiftKind::SuperKeyword,
            595u16 => SwiftKind::FloatLiteralExpression,
            596u16 => SwiftKind::StringLiteralExpression,
            597u16 => SwiftKind::RegexLiteralExpression,
            598u16 => SwiftKind::BooleanLiteralExpression,
            599u16 => SwiftKind::NilLiteralExpression,
            600u16 => SwiftKind::Nil,
            601u16 => SwiftKind::CollectionExpression,
            602u16 => SwiftKind::CollectionElement,
            625u16 => SwiftKind::EffectsAttributeArgumentList,
            626u16 => SwiftKind::EffectsAttributeOperator,
            627u16 => SwiftKind::EffectsAttributeBackslash,
            629u16 => SwiftKind::SpecializeAttributeArgumentList,
            630u16 => SwiftKind::SpecializeTargetFunctionArgument,
            631u16 => SwiftKind::Target,
            633u16 => SwiftKind::SpecializeAvailabilityArgument,
            634u16 => SwiftKind::Availability,
            635u16 => SwiftKind::LabeledSpecializeArgument,
            636u16 => SwiftKind::Exported,
            637u16 => SwiftKind::Kind,
            638u16 => SwiftKind::Spi,
            639u16 => SwiftKind::SpiModule,
            640u16 => SwiftKind::SpecializedAttributeArgument,
            641u16 => SwiftKind::DifferentiableAttributeArguments,
            642u16 => SwiftKind::ForwardDifferentiabilityKeyword,
            643u16 => SwiftKind::Reverse,
            644u16 => SwiftKind::LinearDifferentiabilityKeyword,
            645u16 => SwiftKind::DifferentiabilityWithRespectToArgument,
            646u16 => SwiftKind::Wrt,
            647u16 => SwiftKind::DifferentiabilityArgument,
            648u16 => SwiftKind::DifferentiabilityArguments,
            649u16 => SwiftKind::DifferentiabilityArgumentList,
            650u16 => SwiftKind::DerivativeAttributeArguments,
            656u16 => SwiftKind::ABIAttributeArguments,
            658u16 => SwiftKind::AttributeArgument,
            659u16 => SwiftKind::AttributeArgumentGroup,
            660u16 => SwiftKind::AttributeBracketClause,
            661u16 => SwiftKind::AttributeBraceClause,
            662u16 => SwiftKind::AttributeArgumentKeyword,
            663u16 => SwiftKind::InvalidUsingDeclaration,
            664u16 => SwiftKind::PoundSourceLocation,
            665u16 => SwiftKind::PoundSourceLocationArguments,
            666u16 => SwiftKind::File,
            667u16 => SwiftKind::Line,
            _ => return None,
        };
        Some(kind)
    }
}
#[derive(Clone, Debug)]
pub struct SwiftSourceFile {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftSourceFile {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::SourceFile) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftSourceFile {
    #[must_use]
    pub fn items(&self) -> rezel_common::TypedChildren<SwiftCodeBlockItem> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
}
#[derive(Clone, Debug)]
pub struct SwiftCodeBlockItem {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftCodeBlockItem {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::CodeBlockItem) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftCodeBlockItem {}
#[derive(Clone, Debug)]
pub struct SwiftImportDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftImportDeclaration {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::ImportDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftImportDeclaration {}
#[derive(Clone, Debug)]
pub struct SwiftVariableDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftVariableDeclaration {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::VariableDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftVariableDeclaration {
    #[must_use]
    pub fn bindings(&self) -> rezel_common::TypedChildren<SwiftPatternBinding> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
}
#[derive(Clone, Debug)]
pub struct SwiftPatternBinding {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftPatternBinding {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::PatternBinding) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftPatternBinding {}
#[derive(Clone, Debug)]
pub struct SwiftFunctionDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftFunctionDeclaration {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::FunctionDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftFunctionDeclaration {
    #[must_use]
    pub fn name(&self) -> Option<SwiftFunctionName> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftFunctionName as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
    #[must_use]
    pub fn parameters(&self) -> Option<SwiftFunctionParameterClause> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftFunctionParameterClause as rezel_common::TypedNode>::downcast_from(
                        node,
                    )
                    .ok()
            })
            .nth(0)
    }
    #[must_use]
    pub fn return_clause(&self) -> Option<SwiftReturnClause> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftReturnClause as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
    #[must_use]
    pub fn body(&self) -> Option<SwiftCodeBlock> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftCodeBlock as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct SwiftFunctionName {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftFunctionName {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::FunctionName) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftFunctionName {}
#[derive(Clone, Debug)]
pub struct SwiftFunctionParameterClause {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftFunctionParameterClause {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::FunctionParameterClause) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftFunctionParameterClause {
    #[must_use]
    pub fn parameters(&self) -> rezel_common::TypedChildren<SwiftFunctionParameter> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
}
#[derive(Clone, Debug)]
pub struct SwiftFunctionParameter {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftFunctionParameter {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::FunctionParameter) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftFunctionParameter {}
#[derive(Clone, Debug)]
pub struct SwiftReturnClause {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftReturnClause {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::ReturnClause) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftReturnClause {}
#[derive(Clone, Debug)]
pub struct SwiftStructDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftStructDeclaration {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::StructDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftStructDeclaration {
    #[must_use]
    pub fn name(&self) -> Option<SwiftTypeName> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftTypeName as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
    #[must_use]
    pub fn members(&self) -> Option<SwiftMemberBlock> {
        self.syntax
            .children()
            .filter_map(|node| {
                <SwiftMemberBlock as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct SwiftMemberBlock {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftMemberBlock {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::MemberBlock) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftMemberBlock {}
#[derive(Clone, Debug)]
pub struct SwiftCodeBlock {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftCodeBlock {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::CodeBlock) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftCodeBlock {
    #[must_use]
    pub fn items(&self) -> rezel_common::TypedChildren<SwiftCodeBlockItem> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
}
#[derive(Clone, Debug)]
pub struct SwiftIdentifier {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftIdentifier {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::Identifier) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftIdentifier {}
#[derive(Clone, Debug)]
pub struct SwiftDollarIdentifier {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftDollarIdentifier {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::DollarIdentifier) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftDollarIdentifier {}
#[derive(Clone, Debug)]
pub struct SwiftTypeName {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftTypeName {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::TypeName) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftTypeName {}
#[derive(Clone, Debug)]
pub struct SwiftStringLiteral {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftStringLiteral {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::StringLiteral) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftStringLiteral {}
#[derive(Clone, Debug)]
pub struct SwiftIntegerLiteral {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for SwiftIntegerLiteral {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(SwiftKind::IntegerLiteral) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl SwiftIntegerLiteral {}
#[derive(Clone, Debug)]
pub enum SwiftDeclaration {
    Import(SwiftImportDeclaration),
    Variable(SwiftVariableDeclaration),
    Function(SwiftFunctionDeclaration),
    Struct(SwiftStructDeclaration),
}
impl rezel_common::TypedNode for SwiftDeclaration {
    type Language = SwiftLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        match <SwiftLanguage as rezel_common::SyntaxLanguage>::kind(&node) {
            Some(SwiftKind::ImportDeclaration) => {
                let typed = <SwiftImportDeclaration as rezel_common::TypedNode>::downcast_from(
                        node,
                    )
                    .expect("kind was checked before generated downcast");
                Ok(Self::Import(typed))
            }
            Some(SwiftKind::VariableDeclaration) => {
                let typed = <SwiftVariableDeclaration as rezel_common::TypedNode>::downcast_from(
                        node,
                    )
                    .expect("kind was checked before generated downcast");
                Ok(Self::Variable(typed))
            }
            Some(SwiftKind::FunctionDeclaration) => {
                let typed = <SwiftFunctionDeclaration as rezel_common::TypedNode>::downcast_from(
                        node,
                    )
                    .expect("kind was checked before generated downcast");
                Ok(Self::Function(typed))
            }
            Some(SwiftKind::StructDeclaration) => {
                let typed = <SwiftStructDeclaration as rezel_common::TypedNode>::downcast_from(
                        node,
                    )
                    .expect("kind was checked before generated downcast");
                Ok(Self::Struct(typed))
            }
            _ => Err(node),
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        match self {
            Self::Import(node) => rezel_common::TypedNode::syntax(node),
            Self::Variable(node) => rezel_common::TypedNode::syntax(node),
            Self::Function(node) => rezel_common::TypedNode::syntax(node),
            Self::Struct(node) => rezel_common::TypedNode::syntax(node),
        }
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        match self {
            Self::Import(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Variable(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Function(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Struct(node) => rezel_common::TypedNode::into_syntax(node),
        }
    }
}
