// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:go:update
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_mut)]
#[repr(C, align(64))]
#[derive(zerocopy::FromBytes, zerocopy::Immutable)]
struct GeneratedTables {
    states: [u32; 3468usize],
    state_data: [u16; 5589usize],
    goto: [u16; 2469usize],
    token_states: [rezel_lr::TokenState; 69usize],
    token_accepts: [rezel_lr::TokenAccept; 52usize],
    token_edges: [rezel_lr::TokenEdge; 174usize],
    token_eof: [rezel_lr::TokenEof; 0usize],
    local_token_3_states: [rezel_lr::TokenState; 4usize],
    local_token_3_accepts: [rezel_lr::TokenAccept; 2usize],
    local_token_3_edges: [rezel_lr::TokenEdge; 3usize],
    local_token_3_eof: [rezel_lr::TokenEof; 0usize],
    local_token_3_precedence: [u16; 1usize],
    dynamic_precedences: [rezel_lr::DynamicPrecedence; 6usize],
}
#[cfg(target_endian = "little")]
static TABLES_LE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.le.bin"
);
#[cfg(target_endian = "big")]
static TABLES_BE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.be.bin"
);
#[cfg(target_endian = "little")]
use TABLES_LE as TABLES;
#[cfg(target_endian = "big")]
use TABLES_BE as TABLES;
static TOKEN_TABLE: rezel_lr::TokenTable = rezel_lr::TokenTable::new(
    &TABLES.token_states,
    &TABLES.token_accepts,
    &TABLES.token_edges,
    &TABLES.token_eof,
);
static LOCAL_TOKEN_3_TABLE: rezel_lr::TokenTable = rezel_lr::TokenTable::new(
    &TABLES.local_token_3_states,
    &TABLES.local_token_3_accepts,
    &TABLES.local_token_3_edges,
    &TABLES.local_token_3_eof,
);
fn specialize_0(
    value: &str,
    _stack: &rezel_lr::Stack,
) -> Option<rezel_lr::SpecializedToken> {
    match value {
        "break" => {
            Some(rezel_lr::SpecializedToken::new(145u16, rezel_lr::Specialize::Replace))
        }
        "case" => {
            Some(rezel_lr::SpecializedToken::new(125u16, rezel_lr::Specialize::Replace))
        }
        "chan" => {
            Some(rezel_lr::SpecializedToken::new(47u16, rezel_lr::Specialize::Replace))
        }
        "const" => {
            Some(rezel_lr::SpecializedToken::new(103u16, rezel_lr::Specialize::Replace))
        }
        "continue" => {
            Some(rezel_lr::SpecializedToken::new(146u16, rezel_lr::Specialize::Replace))
        }
        "default" => {
            Some(rezel_lr::SpecializedToken::new(126u16, rezel_lr::Specialize::Replace))
        }
        "defer" => {
            Some(rezel_lr::SpecializedToken::new(151u16, rezel_lr::Specialize::Replace))
        }
        "else" => {
            Some(rezel_lr::SpecializedToken::new(120u16, rezel_lr::Specialize::Replace))
        }
        "fallthrough" => {
            Some(rezel_lr::SpecializedToken::new(149u16, rezel_lr::Specialize::Replace))
        }
        "false" => {
            Some(rezel_lr::SpecializedToken::new(191u16, rezel_lr::Specialize::Extend))
        }
        "for" => {
            Some(rezel_lr::SpecializedToken::new(131u16, rezel_lr::Specialize::Replace))
        }
        "func" => {
            Some(rezel_lr::SpecializedToken::new(34u16, rezel_lr::Specialize::Replace))
        }
        "go" => {
            Some(rezel_lr::SpecializedToken::new(136u16, rezel_lr::Specialize::Replace))
        }
        "goto" => {
            Some(rezel_lr::SpecializedToken::new(147u16, rezel_lr::Specialize::Replace))
        }
        "if" => {
            Some(rezel_lr::SpecializedToken::new(119u16, rezel_lr::Specialize::Replace))
        }
        "import" => {
            Some(rezel_lr::SpecializedToken::new(9u16, rezel_lr::Specialize::Replace))
        }
        "interface" => {
            Some(rezel_lr::SpecializedToken::new(39u16, rezel_lr::Specialize::Replace))
        }
        "make" => {
            Some(rezel_lr::SpecializedToken::new(79u16, rezel_lr::Specialize::Extend))
        }
        "map" => {
            Some(rezel_lr::SpecializedToken::new(59u16, rezel_lr::Specialize::Replace))
        }
        "new" => {
            Some(rezel_lr::SpecializedToken::new(80u16, rezel_lr::Specialize::Extend))
        }
        "nil" => {
            Some(rezel_lr::SpecializedToken::new(192u16, rezel_lr::Specialize::Extend))
        }
        "package" => {
            Some(rezel_lr::SpecializedToken::new(5u16, rezel_lr::Specialize::Replace))
        }
        "range" => {
            Some(rezel_lr::SpecializedToken::new(134u16, rezel_lr::Specialize::Replace))
        }
        "return" => {
            Some(rezel_lr::SpecializedToken::new(143u16, rezel_lr::Specialize::Replace))
        }
        "select" => {
            Some(rezel_lr::SpecializedToken::new(138u16, rezel_lr::Specialize::Replace))
        }
        "struct" => {
            Some(rezel_lr::SpecializedToken::new(24u16, rezel_lr::Specialize::Replace))
        }
        "switch" => {
            Some(rezel_lr::SpecializedToken::new(122u16, rezel_lr::Specialize::Replace))
        }
        "true" => {
            Some(rezel_lr::SpecializedToken::new(191u16, rezel_lr::Specialize::Extend))
        }
        "type" => {
            Some(rezel_lr::SpecializedToken::new(107u16, rezel_lr::Specialize::Replace))
        }
        "var" => {
            Some(rezel_lr::SpecializedToken::new(113u16, rezel_lr::Specialize::Replace))
        }
        _ => None,
    }
}
fn node_set() -> &'static std::sync::Arc<rezel_common::NodeSet> {
    static NODE_SET: std::sync::OnceLock<std::sync::Arc<rezel_common::NodeSet>> = std::sync::OnceLock::new();
    NODE_SET
        .get_or_init(|| {
            let mut nodes = Vec::new();
            {
                let mut node = rezel_common::NodeType::new(
                    0u16,
                    "⚠",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ERROR,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    1u16,
                    "LineComment",
                    rezel_common::NodeFlags::SKIPPED,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    2u16,
                    "BlockComment",
                    rezel_common::NodeFlags::SKIPPED,
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    3u16,
                    "SourceFile",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    4u16,
                    "PackageClause",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    5u16,
                    "package",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    6u16,
                    "DefName",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    7u16,
                    ";",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    8u16,
                    "ImportDecl",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    9u16,
                    "import",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    10u16,
                    "ImportSpec",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    11u16,
                    ".",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    12u16,
                    "String",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    13u16,
                    ")",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("(")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    14u16,
                    "(",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize(")")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    15u16,
                    "SpecList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    16u16,
                    "ExprStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    17u16,
                    "Number",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    18u16,
                    "Bool",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    19u16,
                    "Nil",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    20u16,
                    "Rune",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    21u16,
                    "VariableName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    22u16,
                    "TypedLiteral",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    23u16,
                    "StructType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    24u16,
                    "struct",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    25u16,
                    "}",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("{")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    26u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("}")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    27u16,
                    "StructBody",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    28u16,
                    "FieldDecl",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    29u16,
                    "FieldName",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    30u16,
                    ",",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    31u16,
                    "PointerType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    32u16,
                    "*",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    33u16,
                    "FunctionType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    34u16,
                    "func",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    35u16,
                    "Parameters",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    36u16,
                    "Parameter",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    37u16,
                    "...",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    38u16,
                    "InterfaceType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    39u16,
                    "interface",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    40u16,
                    "InterfaceBody",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    41u16,
                    "MethodElem",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    42u16,
                    "UnderlyingType",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    43u16,
                    "~",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    44u16,
                    "TypeElem",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    45u16,
                    "LogicOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    46u16,
                    "ChannelType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    47u16,
                    "chan",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    48u16,
                    "<-",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    49u16,
                    "ParenthesizedType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    50u16,
                    "QualifiedType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    51u16,
                    "TypeName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    52u16,
                    "ParameterizedType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    53u16,
                    "]",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("[")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    54u16,
                    "[",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("]")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    55u16,
                    "TypeArgs",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    56u16,
                    "ArrayType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    57u16,
                    "SliceType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    58u16,
                    "MapType",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Type")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    59u16,
                    "map",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    60u16,
                    "LiteralValue",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    61u16,
                    "Element",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    62u16,
                    "Key",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    63u16,
                    ":",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    64u16,
                    "Element",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    65u16,
                    "Key",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    66u16,
                    "ParenthesizedExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    67u16,
                    "FunctionLiteral",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    68u16,
                    "Block",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    69u16,
                    "Conversion",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    70u16,
                    "SelectorExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    71u16,
                    "IndexExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    72u16,
                    "IndexListExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    73u16,
                    "SliceExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    74u16,
                    "TypeAssertion",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    75u16,
                    "CallExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    76u16,
                    "ParameterizedExpr",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    77u16,
                    "Arguments",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    78u16,
                    "CallExpr",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    79u16,
                    "make",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    80u16,
                    "new",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    81u16,
                    "Arguments",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    82u16,
                    "UnaryExp",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    83u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    84u16,
                    "LogicOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    85u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    86u16,
                    "DerefOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    87u16,
                    "BinaryExp",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Expr")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    88u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    89u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    90u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    91u16,
                    "CompareOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    92u16,
                    "LogicOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    93u16,
                    "LogicOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    94u16,
                    "SendStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    95u16,
                    "IncDecStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    96u16,
                    "IncDecOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    97u16,
                    "Assignment",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    98u16,
                    "=",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    99u16,
                    "UpdateOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    100u16,
                    "VarDecl",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    101u16,
                    ":=",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    102u16,
                    "ConstDecl",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    103u16,
                    "const",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    104u16,
                    "ConstSpec",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    105u16,
                    "SpecList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    106u16,
                    "TypeDecl",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    107u16,
                    "type",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    108u16,
                    "TypeSpec",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    109u16,
                    "TypeParams",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    110u16,
                    "TypeParam",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    111u16,
                    "SpecList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    112u16,
                    "VarDecl",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    113u16,
                    "var",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    114u16,
                    "VarSpec",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    115u16,
                    "SpecList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    116u16,
                    "LabeledStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    117u16,
                    "LabelName",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    118u16,
                    "IfStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    119u16,
                    "if",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    120u16,
                    "else",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    121u16,
                    "SwitchStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    122u16,
                    "switch",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    123u16,
                    "SwitchBlock",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    124u16,
                    "Case",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    125u16,
                    "case",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    126u16,
                    "default",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    127u16,
                    "TypeSwitchStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    128u16,
                    "SwitchBlock",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    129u16,
                    "Case",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    130u16,
                    "ForStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    131u16,
                    "for",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    132u16,
                    "ForClause",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    133u16,
                    "RangeClause",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    134u16,
                    "range",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    135u16,
                    "GoStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    136u16,
                    "go",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    137u16,
                    "SelectStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    138u16,
                    "select",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    139u16,
                    "SelectBlock",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    140u16,
                    "Case",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    141u16,
                    "ReceiveStatement",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    142u16,
                    "ReturnStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    143u16,
                    "return",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    144u16,
                    "GotoStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    145u16,
                    "break",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    146u16,
                    "continue",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    147u16,
                    "goto",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    148u16,
                    "FallthroughStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    149u16,
                    "fallthrough",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    150u16,
                    "DeferStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    151u16,
                    "defer",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    152u16,
                    "FunctionDecl",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    153u16,
                    "MethodDecl",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    154u16,
                    "",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    155u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    156u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    157u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    158u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    159u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    160u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    161u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    162u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    163u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    164u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    165u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    166u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    167u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    168u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    169u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    170u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    171u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    172u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    173u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    174u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    175u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    176u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            std::sync::Arc::new(
                rezel_common::NodeSet::new(nodes).extend(&[crate::go_highlighting()]),
            )
        })
}
static TOKENIZERS: &[rezel_lr::Tokenizer] = &[
    rezel_lr::Tokenizer::External(&crate::tokens::SEMICOLON),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(1u8)),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(2u8)),
    rezel_lr::Tokenizer::Local(
        rezel_lr::LocalTokenGroup::new(
            &LOCAL_TOKEN_3_TABLE,
            &TABLES.local_token_3_precedence,
            Some(182u16),
        ),
    ),
];
static TOP_RULES: &[rezel_lr::TopRule] = &[
    rezel_lr::TopRule {
        name: "SourceFile",
        state: 0u16,
        term: 3u16,
    },
];
static DIALECTS: &[rezel_lr::DialectSpec] = &[];
static SPECIALIZERS: &[rezel_lr::SpecializerSpec] = &[
    rezel_lr::SpecializerSpec {
        term: 185u16,
        get: specialize_0,
    },
];
static TERM_NAMES: &[(u16, &str)] = &[
    (0u16, "⚠"),
    (1u16, "LineComment"),
    (2u16, "BlockComment"),
    (3u16, "@top"),
    (4u16, "PackageClause"),
    (5u16, "identifier/\"package\""),
    (6u16, "DefName"),
    (7u16, "\";\""),
    (8u16, "ImportDecl"),
    (9u16, "identifier/\"import\""),
    (10u16, "ImportSpec"),
    (11u16, "\".\""),
    (12u16, "String"),
    (13u16, "\")\""),
    (14u16, "\"(\""),
    (15u16, "SpecList<ImportSpec>"),
    (16u16, "ExprStatement"),
    (17u16, "Number"),
    (18u16, "Bool"),
    (19u16, "Nil"),
    (20u16, "Rune"),
    (21u16, "VariableName"),
    (22u16, "TypedLiteral"),
    (23u16, "StructType"),
    (24u16, "identifier/\"struct\""),
    (25u16, "\"}\""),
    (26u16, "\"{\""),
    (27u16, "StructBody"),
    (28u16, "FieldDecl"),
    (29u16, "FieldName"),
    (30u16, "\",\""),
    (31u16, "PointerType"),
    (32u16, "star"),
    (33u16, "FunctionType"),
    (34u16, "identifier/\"func\""),
    (35u16, "Parameters"),
    (36u16, "Parameter"),
    (37u16, "\"...\""),
    (38u16, "InterfaceType"),
    (39u16, "identifier/\"interface\""),
    (40u16, "InterfaceBody"),
    (41u16, "MethodElem"),
    (42u16, "UnderlyingType"),
    (43u16, "\"~\""),
    (44u16, "TypeElem"),
    (45u16, "LogicOp<\"|\">"),
    (46u16, "ChannelType"),
    (47u16, "identifier/\"chan\""),
    (48u16, "\"<-\""),
    (49u16, "ParenthesizedType"),
    (50u16, "QualifiedType"),
    (51u16, "TypeName"),
    (52u16, "ParameterizedType"),
    (53u16, "\"]\""),
    (54u16, "\"[\""),
    (55u16, "TypeArgs"),
    (56u16, "ArrayType"),
    (57u16, "SliceType"),
    (58u16, "MapType"),
    (59u16, "identifier/\"map\""),
    (60u16, "LiteralValue"),
    (61u16, "Element"),
    (62u16, "Key"),
    (63u16, "\":\""),
    (64u16, "Element-1"),
    (65u16, "Key-1"),
    (66u16, "ParenthesizedExpr"),
    (67u16, "FunctionLiteral"),
    (68u16, "Block"),
    (69u16, "Conversion"),
    (70u16, "SelectorExpr"),
    (71u16, "IndexExpr"),
    (72u16, "IndexListExpr"),
    (73u16, "SliceExpr"),
    (74u16, "TypeAssertion"),
    (75u16, "CallExpr"),
    (76u16, "ParameterizedExpr"),
    (77u16, "Arguments"),
    (78u16, "CallExpr-1"),
    (79u16, "identifier/\"make\""),
    (80u16, "identifier/\"new\""),
    (81u16, "newArguments"),
    (82u16, "UnaryExp"),
    (83u16, "ArithOp<\"+\" | \"-\">"),
    (84u16, "LogicOp<\"!\">"),
    (85u16, "BitOp<\"^\">"),
    (86u16, "DerefOp<\"*\" | \"&\">"),
    (87u16, "BinaryExp"),
    (88u16, "ArithOp<\"*\" | \"/\" | \"%\">"),
    (89u16, "BitOp<\"<<\" | \">>\" | \"&\" | \"&^\">"),
    (90u16, "BitOp<\"|\" | \"^\">"),
    (91u16, "CompareOp"),
    (92u16, "LogicOp<\"&&\">"),
    (93u16, "LogicOp<\"||\">"),
    (94u16, "SendStatement"),
    (95u16, "IncDecStatement"),
    (96u16, "IncDecOp"),
    (97u16, "Assignment"),
    (98u16, "\"=\""),
    (99u16, "UpdateOp"),
    (100u16, "shortVarDecl"),
    (101u16, "\":=\""),
    (102u16, "ConstDecl"),
    (103u16, "identifier/\"const\""),
    (104u16, "ConstSpec"),
    (105u16, "SpecList<ConstSpec>"),
    (106u16, "TypeDecl"),
    (107u16, "identifier/\"type\""),
    (108u16, "TypeSpec"),
    (109u16, "TypeParams"),
    (110u16, "TypeParam"),
    (111u16, "SpecList<TypeSpec>"),
    (112u16, "VarDecl"),
    (113u16, "identifier/\"var\""),
    (114u16, "VarSpec"),
    (115u16, "SpecList<VarSpec>"),
    (116u16, "LabeledStatement"),
    (117u16, "LabelName"),
    (118u16, "IfStatement"),
    (119u16, "identifier/\"if\""),
    (120u16, "identifier/\"else\""),
    (121u16, "SwitchStatement"),
    (122u16, "identifier/\"switch\""),
    (123u16, "SwitchBlock"),
    (124u16, "Case<exprList>"),
    (125u16, "identifier/\"case\""),
    (126u16, "identifier/\"default\""),
    (127u16, "TypeSwitchStatement"),
    (128u16, "typeSwitchBlock"),
    (129u16, "Case<commaSep1<type>>"),
    (130u16, "ForStatement"),
    (131u16, "identifier/\"for\""),
    (132u16, "ForClause"),
    (133u16, "RangeClause"),
    (134u16, "identifier/\"range\""),
    (135u16, "GoStatement"),
    (136u16, "identifier/\"go\""),
    (137u16, "SelectStatement"),
    (138u16, "identifier/\"select\""),
    (139u16, "SelectBlock"),
    (140u16, "Case<SendStatement | ReceiveStatement>"),
    (141u16, "ReceiveStatement"),
    (142u16, "ReturnStatement"),
    (143u16, "identifier/\"return\""),
    (144u16, "GotoStatement"),
    (145u16, "identifier/\"break\""),
    (146u16, "identifier/\"continue\""),
    (147u16, "identifier/\"goto\""),
    (148u16, "FallthroughStatement"),
    (149u16, "identifier/\"fallthrough\""),
    (150u16, "DeferStatement"),
    (151u16, "identifier/\"defer\""),
    (152u16, "FunctionDecl"),
    (153u16, "MethodDecl"),
    (154u16, "blockCommentContent | blockCommentNewline+"),
    (155u16, "ImportDecl semi+"),
    (156u16, "ImportSpec semi+"),
    (157u16, "statement | FunctionDecl | MethodDecl semi | \";\"+"),
    (158u16, "FieldDecl semi+"),
    (159u16, "\",\" FieldName+"),
    (160u16, "\",\" DefName+"),
    (161u16, "\",\" Parameter+"),
    (162u16, "MethodElem | typeElem semi+"),
    (163u16, "LogicOp<\"|\"> typeOrUnderlying+"),
    (164u16, "VariableName \".\"+"),
    (165u16, "\",\" type+"),
    (166u16, "\",\" Element+"),
    (167u16, "statement semi | \";\"+"),
    (168u16, "\",\" expr?+"),
    (169u16, "ConstSpec semi+"),
    (170u16, "\",\" typeName+"),
    (171u16, "\",\" TypeParam+"),
    (172u16, "TypeSpec semi+"),
    (173u16, "VarSpec semi+"),
    (174u16, "Case<exprList> semiSep<statement>+"),
    (175u16, "Case<commaSep1<type>> semiSep<statement>+"),
    (176u16, "Case<SendStatement | ReceiveStatement> semiSep<statement>+"),
    (177u16, "␄"),
    (178u16, "insertedSemi"),
    (179u16, "%mainskip-1"),
    (180u16, "space"),
    (181u16, "\"/*\""),
    (182u16, "blockCommentContent"),
    (183u16, "blockCommentNewline"),
    (184u16, "blockCommentEnd"),
    (185u16, "identifier"),
    (186u16, "semi-1"),
    (187u16, "semiSep<statement | FunctionDecl | MethodDecl>-1"),
    (188u16, "statement-1"),
    (189u16, "simpleStatement-1"),
    (190u16, "expr-1"),
    (191u16, "identifier/\"true\""),
    (192u16, "identifier/\"nil\""),
    (193u16, "literalType-1"),
    (194u16, "type-1"),
    (195u16, "\"*\""),
    (196u16, "signature-1"),
    (197u16, "commaSep<Parameter>-1"),
    (198u16, "idList-1"),
    (199u16, "typeElem-1"),
    (200u16, "typeOrUnderlying-1"),
    (201u16, "\"|\""),
    (202u16, "typeName-1"),
    (203u16, "commaSep1<type>-1"),
    (204u16, "commaSep<Element>-1"),
    (205u16, "semiSep<statement>-1"),
    (206u16, "exprList-1"),
    (207u16, "\"+\""),
    (208u16, "\"-\""),
    (209u16, "\"!\""),
    (210u16, "\"^\""),
    (211u16, "\"&\""),
    (212u16, "\"/\""),
    (213u16, "\"%\""),
    (214u16, "\"<<\""),
    (215u16, "\">>\""),
    (216u16, "\"&^\""),
    (217u16, "\"&&\""),
    (218u16, "\"||\""),
    (219u16, "commaSep1<TypeParam>-1"),
];
pub static LANGUAGE: rezel_lr::Language = rezel_lr::Language {
    states: &TABLES.states,
    state_data: &TABLES.state_data,
    goto: &TABLES.goto,
    token_table: &TOKEN_TABLE,
    tokenizers: TOKENIZERS,
    top_rules: TOP_RULES,
    max_term: 219u16,
    min_repeat_term: 154u16,
    token_precedence: 5584usize,
    node_set,
    context: Some(&crate::tokens::TRACK_TOKENS),
    dialects: DIALECTS,
    dynamic_precedences: &TABLES.dynamic_precedences,
    specializers: SPECIALIZERS,
    term_names: TERM_NAMES,
};
