[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftMetatypeTokens"
rust_path = "crate::tokens::METATYPE_TOKENS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftKeywordIdentifiers"
rust_path = "crate::tokens::KEYWORD_IDENTIFIERS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftGenericRequirementContinuation"
rust_path = "crate::tokens::GENERIC_REQUIREMENT_CONTINUATION"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftCodeItemLayout"
rust_path = "crate::tokens::CODE_ITEM_LAYOUT"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftAccessorLookaheads"
rust_path = "crate::tokens::ACCESSOR_LOOKAHEADS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftTypePathLookaheads"
rust_path = "crate::tokens::TYPE_PATH_LOOKAHEADS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftAttributeTokens"
rust_path = "crate::tokens::ATTRIBUTE_TOKENS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftLiterals"
rust_path = "crate::tokens::LITERALS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftGenericValueLookaheads"
rust_path = "crate::tokens::GENERIC_VALUE_LOOKAHEADS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftSyntaxLookaheads"
rust_path = "crate::tokens::SYNTAX_LOOKAHEADS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftOperators"
rust_path = "crate::tokens::OPERATORS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftCatchPatternContext"
rust_path = "crate::tokens::CATCH_PATTERN_CONTEXT"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "swiftClosureSignatureContext"
rust_path = "crate::tokens::CLOSURE_SIGNATURE_CONTEXT"
