// @generated by rezel-codegen. Do not edit manually.
// Regenerate with: mise run codegen:rezel:fixtures:update
pub struct GeneratedCase {
    pub name: &'static str,
    pub language: &'static rezel_lr::Language,
}

macro_rules! generated_cases {
    ($($name:literal => $module:ident @ $path:literal;)*) => {
        $(
            #[path = $path]
            #[rustfmt::skip]
            pub mod $module;
        )*

        pub static CASES: &[GeneratedCase] = &[
            $(
                GeneratedCase {
                    name: $name,
                    language: &$module::LANGUAGE,
                },
            )*
        ];
    };
}

generated_cases! {
    "AlternativeTop" => alternative_top @ "../generated/cases/alternative_top.rs";
    "AnyChar" => any_char @ "../generated/cases/any_char.rs";
    "Astral" => astral @ "../generated/cases/astral.rs";
    "AstralRuleName" => astral_rule_name @ "../generated/cases/astral_rule_name.rs";
    "AutoDelimTag" => auto_delim_tag @ "../generated/cases/auto_delim_tag.rs";
    "BinaryExpr" => binary_expr @ "../generated/cases/binary_expr.rs";
    "Conflict" => conflict @ "../generated/cases/conflict.rs";
    "Cut" => cut @ "../generated/cases/cut.rs";
    "DeepBinary" => deep_binary @ "../generated/cases/deep_binary.rs";
    "DeepConflict" => deep_conflict @ "../generated/cases/deep_conflict.rs";
    "DefineGroup" => define_group @ "../generated/cases/define_group.rs";
    "Dialect" => dialect @ "../generated/cases/dialect.rs";
    "DynamicPrecedence" => dynamic_precedence @ "../generated/cases/dynamic_precedence.rs";
    "EmptyAfterLookahead" => empty_after_lookahead @ "../generated/cases/empty_after_lookahead.rs";
    "EmptyExpressions" => empty_expressions @ "../generated/cases/empty_expressions.rs";
    "Eof" => eof @ "../generated/cases/eof.rs";
    "ExplicitInline" => explicit_inline @ "../generated/cases/explicit_inline.rs";
    "ExternalProp" => external_prop @ "../generated/cases/external_prop.rs";
    "ExternalSpecializer" => external_specializer @ "../generated/cases/external_specializer.rs";
    "ExternalTokens" => external_tokens @ "../generated/cases/external_tokens.rs";
    "ForcedSkipReduce" => forced_skip_reduce @ "../generated/cases/forced_skip_reduce.rs";
    "InlineRule" => inline_rule @ "../generated/cases/inline_rule.rs";
    "LocalTokenSpecialize" => local_token_specialize @ "../generated/cases/local_token_specialize.rs";
    "LocalTokens" => local_tokens @ "../generated/cases/local_tokens.rs";
    "LongerToken" => longer_token @ "../generated/cases/longer_token.rs";
    "NameRules" => name_rules @ "../generated/cases/name_rules.rs";
    "NodeDeclaration" => node_declaration @ "../generated/cases/node_declaration.rs";
    "NotLALR" => not_l_a_l_r @ "../generated/cases/not_l_a_l_r.rs";
    "PrecedenceOrder" => precedence_order @ "../generated/cases/precedence_order.rs";
    "Recover" => recover @ "../generated/cases/recover.rs";
    "RecoverInsertInParent" => recover_insert_in_parent @ "../generated/cases/recover_insert_in_parent.rs";
    "RecoverRecursiveEof" => recover_recursive_eof @ "../generated/cases/recover_recursive_eof.rs";
    "ScopedSkip" => scoped_skip @ "../generated/cases/scoped_skip.rs";
    "SeparateConflictingTokens" => separate_conflicting_tokens @ "../generated/cases/separate_conflicting_tokens.rs";
    "SkipExpr" => skip_expr @ "../generated/cases/skip_expr.rs";
    "SkipPosition" => skip_position @ "../generated/cases/skip_position.rs";
    "Specialize" => specialize @ "../generated/cases/specialize.rs";
    "TailRecursiveToken" => tail_recursive_token @ "../generated/cases/tail_recursive_token.rs";
    "TokenArgs" => token_args @ "../generated/cases/token_args.rs";
    "TokenExpr" => token_expr @ "../generated/cases/token_expr.rs";
    "TokenGroups" => token_groups @ "../generated/cases/token_groups.rs";
    "TokenPrecedence" => token_precedence @ "../generated/cases/token_precedence.rs";
    "TopName" => top_name @ "../generated/cases/top_name.rs";
    "TrailingComma" => trailing_comma @ "../generated/cases/trailing_comma.rs";
    "Tuple" => tuple @ "../generated/cases/tuple.rs";
    "Whitespace" => whitespace @ "../generated/cases/whitespace.rs";
    "ZeroLengthReduction" => zero_length_reduction @ "../generated/cases/zero_length_reduction.rs";
}
