import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

public final class JdkIdentifierTables {
    private static final int JAVA_RELEASE = 26;
    private static final int MAX_CODE_POINT = Character.MAX_CODE_POINT;
    private static final String REGENERATION_COMMAND =
            "mise run codegen:java-identifiers:update";

    private JdkIdentifierTables() {}

    public static void main(String[] arguments) throws IOException {
        if (arguments.length != 2
                || !(arguments[0].equals("--check") || arguments[0].equals("--write"))) {
            throw new IllegalArgumentException(
                    "usage: JdkIdentifierTables.java (--check|--write) OUTPUT.rs");
        }
        if (Runtime.version().feature() != JAVA_RELEASE) {
            throw new IllegalStateException("Java 26 is required");
        }

        String output =
                render(
                        collect(Character::isJavaIdentifierStart),
                        collect(Character::isJavaIdentifierPart),
                        collect(Character::isIdentifierIgnorable));
        Path path = Path.of(arguments[1]);
        if (arguments[0].equals("--write")) {
            Files.writeString(path, output, StandardCharsets.UTF_8);
            return;
        }

        String checked = Files.readString(path, StandardCharsets.UTF_8);
        if (!checked.equals(output)) {
            throw new IllegalStateException(path + " is not generated from Java 26");
        }
    }

    private static List<Range> collect(CodePointPredicate predicate) {
        List<Range> output = new ArrayList<>();
        int start = -1;
        for (int codePoint = 0; codePoint <= MAX_CODE_POINT; codePoint++) {
            boolean accepted =
                    Character.isValidCodePoint(codePoint)
                            && (codePoint < Character.MIN_SURROGATE
                                    || codePoint > Character.MAX_SURROGATE)
                            && predicate.test(codePoint);
            if (accepted && start < 0) {
                start = codePoint;
            } else if (!accepted && start >= 0) {
                output.add(new Range(start, codePoint - 1));
                start = -1;
            }
        }
        if (start >= 0) {
            output.add(new Range(start, MAX_CODE_POINT));
        }
        return List.copyOf(output);
    }

    private static String render(
            List<Range> start, List<Range> part, List<Range> ignorable) {
        StringBuilder output = new StringBuilder();
        output.append(
                "// @generated by tools/references/javac/java/JdkIdentifierTables.java."
                        + " Do not edit manually.\n");
        output.append("// Regenerate with: ").append(REGENERATION_COMMAND).append('\n');
        output.append("// Java 26 Character identifier properties (Unicode 17.0)\n");
        output.append('\n');
        renderRanges(output, "JAVA_IDENTIFIER_START", start);
        output.append('\n');
        renderRanges(output, "JAVA_IDENTIFIER_PART", part);
        output.append('\n');
        renderRanges(output, "JAVA_IDENTIFIER_IGNORABLE", ignorable);
        return output.toString();
    }

    private static void renderRanges(
            StringBuilder output, String name, List<Range> ranges) {
        output.append("pub(super) static ")
                .append(name)
                .append(": &[(u32, u32)] = &[\n");
        for (Range range : ranges) {
            output.append("    (0x")
                    .append(Integer.toHexString(range.start()))
                    .append(", 0x")
                    .append(Integer.toHexString(range.end()))
                    .append("),\n");
        }
        output.append("];\n");
    }

    @FunctionalInterface
    private interface CodePointPredicate {
        boolean test(int codePoint);
    }

    private record Range(int start, int end) {}
}
