[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "closureParam"
rust_path = "crate::tokens::CLOSURE_PARAM"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "tpDelim"
rust_path = "crate::tokens::TYPE_PARAMETER_DELIMITERS"

[[binding]]
kind = "external-tokenizer"
source = "./tokens"
name = "literalTokens"
rust_path = "crate::tokens::LITERALS"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "rustMacroRules"
rust_path = "crate::identifier::MACRO_RULES_TOKENIZER"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "rustTokenIdentifiers"
rust_path = "crate::identifier::TOKEN_IDENTIFIER_TOKENIZER"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "rustIdentifiers"
rust_path = "crate::identifier::IDENTIFIER_TOKENIZER"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "rustLifetimes"
rust_path = "crate::identifier::LIFETIME_TOKENIZER"

[[binding]]
kind = "external-tokenizer"
source = "./identifier"
name = "rustMetavariables"
rust_path = "crate::identifier::METAVARIABLE_TOKENIZER"

[[binding]]
kind = "property-source"
source = "./highlight"
name = "rustHighlighting"
rust_path = "crate::rust_highlighting"
