use crate::GeneratorError;

const GENERATED_HEADER: &str = "// @generated by rezel-generator. Do not edit manually.\n";

pub(crate) fn format_generated_rust(
    source: &str,
    invalid_source_message: &str,
) -> Result<String, GeneratorError> {
    let parsed = syn::parse_file(source)
        .map_err(|error| GeneratorError::new(format!("{invalid_source_message}: {error}"), None))?;
    let formatted = prettyplease::unparse(&parsed);
    let mut generated = String::with_capacity(GENERATED_HEADER.len() + formatted.len());
    generated.push_str(GENERATED_HEADER);
    generated.push_str(&formatted);
    Ok(generated)
}

#[cfg(test)]
mod tests {
    use super::{GENERATED_HEADER, format_generated_rust};

    #[test]
    fn prepends_the_generated_marker_after_formatting() {
        let generated =
            format_generated_rust("fn generated( ){ }", "invalid generated source").unwrap();
        assert_eq!(
            generated,
            format!("{GENERATED_HEADER}fn generated() {{}}\n")
        );
    }
}
