#!/usr/bin/env python3
"""Generate Rust Python AST kind and field enums from the CPython snapshot."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SNAPSHOT = ROOT / "tools" / "references" / "cpython" / "snapshots" / "python.json"
OUTPUT = ROOT / "languages" / "python" / "src" / "ast" / "schema.rs"
REGENERATION_COMMAND = "mise run codegen:python-ast:update"


def rust_name(value: str, abstract_lower: bool) -> str:
    words = re.findall(r"[A-Za-z0-9]+", value)
    result = "".join(word[:1].upper() + word[1:] for word in words)
    if abstract_lower and value[:1].islower():
        result = "Abstract" + result
    return "Type" if result == "Type" else result


def enum(name: str, values: list[str], method: str, abstract_lower: bool) -> str:
    lines = [
        "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]",
        "#[non_exhaustive]",
        f"pub enum {name} {{",
    ]
    lines.extend(f"    {rust_name(value, abstract_lower)}," for value in values)
    lines.extend(
        [
            "}",
            "",
            f"impl {name} {{",
            "    #[must_use]",
            f"    pub const fn {method}(self) -> &'static str {{",
            "        match self {",
        ]
    )
    lines.extend(
        f'            Self::{rust_name(value, abstract_lower)} => "{value}",'
        for value in values
    )
    lines.extend(["        }", "    }", "}", ""])
    return "\n".join(lines)


def generate() -> str:
    snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    if snapshot["pythonVersion"] != "3.14.5":
        raise SystemExit("AST schema source is not CPython 3.14.5")
    kinds = sorted(item["name"] for item in snapshot["astSchema"])
    fields = sorted(
        {
            field
            for item in snapshot["astSchema"]
            for field in item["fields"]
        }
    )
    return (
        "// @generated by tools/references/cpython/ast_schema.py. "
        "Do not edit manually.\n"
        f"// Regenerate with: {REGENERATION_COMMAND}\n"
        "#![allow(clippy::too_many_lines)] // Exhaustive generated name tables.\n\n"
        + enum("PythonAstKind", kinds, "python_name", True)
        + "\n"
        + enum("PythonAstField", fields, "python_name", False)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.update:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
    elif OUTPUT.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"Python AST schema is stale; run `{REGENERATION_COMMAND}`")


if __name__ == "__main__":
    main()
