#!/usr/bin/env python3
"""Generate the complete Python typed CST schema from kinds and a semantic model."""

from __future__ import annotations

import argparse
import json
import keyword
import re
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
GENERATED = ROOT / "languages" / "python" / "src" / "generated.rs"
SCHEMA = ROOT / "languages" / "python" / "src" / "python.typed.toml"
MODEL = ROOT / "languages" / "python" / "src" / "python.typed.model.toml"
REGENERATION_COMMAND = "mise run codegen:python-typed:update"
NODE = re.compile(
    r'NodeType::new\(\s*\d+u16,\s*"((?:[^"\\]|\\.)*)",',
    re.MULTILINE,
)

PUNCTUATION_NAMES = {
    "⚠": "Error",
    "(": "LeftParen",
    ")": "RightParen",
    "[": "LeftBracket",
    "]": "RightBracket",
    "{": "LeftBrace",
    "}": "RightBrace",
    ":": "Colon",
    ",": "Comma",
    ";": "Semicolon",
    ".": "Dot",
    "@": "AtToken",
    "*": "Star",
    "**": "DoubleStar",
    "=": "Equal",
    "->": "Arrow",
    "...": "EllipsisToken",
}


def rust_name(kind: str) -> str:
    if kind in PUNCTUATION_NAMES:
        return PUNCTUATION_NAMES[kind]
    words = re.findall(r"[A-Za-z0-9]+", kind)
    if not words:
        raise ValueError(f"cannot derive Rust name for {kind!r}")
    value = "".join(word[:1].upper() + word[1:] for word in words)
    if keyword.iskeyword(kind) or kind.islower():
        value += "Keyword"
    if value[0].isdigit():
        value = "Kind" + value
    return value


def generate() -> str:
    source = GENERATED.read_text(encoding="utf-8")
    kinds = sorted(
        {
            json.loads(f'"{name}"')
            for name in NODE.findall(source)
            if name
        }
    )
    names: dict[str, str] = {}
    used: set[str] = set()
    for kind in kinds:
        candidate = rust_name(kind)
        while candidate in used:
            candidate += "Node"
        used.add(candidate)
        names[kind] = candidate

    model_source = MODEL.read_text(encoding="utf-8")
    model = tomllib.loads(model_source)
    model_nodes = model.get("node", [])
    overridden_kinds: set[str] = set()
    overridden_names: set[str] = set()
    for node in model_nodes:
        kind = node["kind"]
        name = node["name"]
        if kind not in names:
            raise ValueError(f"semantic typed model refers to unknown kind {kind!r}")
        if kind in overridden_kinds:
            raise ValueError(f"semantic typed model repeats kind {kind!r}")
        if name in overridden_names:
            raise ValueError(f"semantic typed model repeats node name {name!r}")
        expected_name = f"Python{names[kind]}"
        if name != expected_name:
            raise ValueError(
                f"semantic typed model names {kind!r} {name!r}; expected {expected_name!r}"
            )
        overridden_kinds.add(kind)
        overridden_names.add(name)

    lines = [
        "# @generated by tools/references/cpython/typed_schema.py. "
        "Do not edit manually.",
        f"# Regenerate with: {REGENERATION_COMMAND}",
        "",
        'language = "PythonLanguage"',
        'kind = "PythonKind"',
        'language_path = "crate::generated::LANGUAGE"',
        'coverage = "complete"',
        "",
        "[kind_names]",
    ]
    for kind in kinds:
        lines.append(f"{kind!r} = {names[kind]!r}")
    for kind in kinds:
        if kind in overridden_kinds:
            continue
        lines.extend(
            [
                "",
                "[[node]]",
                f'name = "Python{names[kind]}"',
                f"kind = {kind!r}",
            ]
        )
    if model_source.strip():
        lines.extend(
            [
                "",
                "# Semantic fields and unions are maintained in python.typed.model.toml.",
                model_source.strip(),
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.update:
        SCHEMA.write_text(generated, encoding="utf-8")
    elif SCHEMA.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"Python typed schema is stale; run `{REGENERATION_COMMAND}`")


if __name__ == "__main__":
    main()
