#!/usr/bin/env python3
"""Generate Python 3.14 Unicode identifier tables for the Rust tokenizer."""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path


EXPECTED_PYTHON = (3, 14, 5)
EXPECTED_UNICODE = "16.0.0"
REGENERATION_COMMAND = "mise run codegen:python-unicode:update"


def ranges(predicate: object) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    start: int | None = None
    end = 0
    for value in range(sys.maxunicode + 1):
        if 0xD800 <= value <= 0xDFFF:
            matches = False
        else:
            matches = predicate(chr(value))  # type: ignore[operator]
        if matches:
            if start is None:
                start = value
            end = value
        elif start is not None:
            result.append((start, end))
            start = None
    if start is not None:
        result.append((start, end))
    return result


def emit_table(name: str, values: list[tuple[int, int]]) -> str:
    lines = [f"pub(crate) static {name}: &[(u32, u32)] = &["]
    lines.extend(f"    (0x{start:x}, 0x{end:x})," for start, end in values)
    lines.append("];")
    return "\n".join(lines)


def generate() -> str:
    if sys.version_info[:3] != EXPECTED_PYTHON:
        raise SystemExit(
            f"expected CPython {EXPECTED_PYTHON}, got {sys.version_info[:3]}"
        )
    if unicodedata.unidata_version != EXPECTED_UNICODE:
        raise SystemExit(
            f"expected Unicode {EXPECTED_UNICODE}, got {unicodedata.unidata_version}"
        )
    starts = ranges(lambda char: char == "_" or char.isidentifier())
    continues = ranges(lambda char: ("A" + char).isidentifier())
    return (
        "// @generated by tools/references/cpython/unicode_tables.py. "
        "Do not edit manually.\n"
        f"// Regenerate with: {REGENERATION_COMMAND}\n"
        f'pub(crate) const UNICODE_VERSION: &str = "{EXPECTED_UNICODE}";\n\n'
        f"{emit_table('XID_START', starts)}\n\n"
        f"{emit_table('XID_CONTINUE', continues)}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", type=Path)
    mode.add_argument("--write", type=Path)
    args = parser.parse_args()
    generated = generate()
    if args.write is not None:
        args.write.write_text(generated, encoding="utf-8")
        return
    current = args.check.read_text(encoding="utf-8")
    if current != generated:
        raise SystemExit(f"{args.check} is stale; run `{REGENERATION_COMMAND}`")


if __name__ == "__main__":
    main()
