#!/usr/bin/env python3
"""Generate CPython 3.14 Unicode 16 formal name-alias tables."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import unicodedata
from pathlib import Path


EXPECTED_PYTHON = (3, 14, 5)
EXPECTED_UNICODE = "16.0.0"
EXPECTED_SOURCE_SHA256 = (
    "9953f0fcebf5ea8091c5c581e4df0e43f20d2533c84ccca7987a9bb819a896a8"
)
DATA = Path(__file__).with_name("data") / "NameAliases-16.0.0.txt"
REGENERATION_COMMAND = "mise run codegen:python-unicode-names:update"


def aliases() -> list[tuple[str, int]]:
    source = DATA.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    if digest != EXPECTED_SOURCE_SHA256:
        raise SystemExit(f"{DATA} has unexpected SHA-256 {digest}")

    result: list[tuple[str, int]] = []
    for raw_line in source.decode("utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        code_point, alias, _kind = line.split(";")
        value = int(code_point, 16)
        resolved = unicodedata.lookup(alias)
        if len(resolved) != 1 or ord(resolved) != value:
            raise SystemExit(
                f"CPython lookup disagrees with {alias!r}: "
                f"U+{value:04X} != {resolved!r}"
            )
        result.append((alias, value))

    result.sort()
    if len(result) != 477:
        raise SystemExit(f"expected 477 Unicode name aliases, got {len(result)}")
    return result


def generate() -> str:
    if sys.version_info[:3] != EXPECTED_PYTHON:
        raise SystemExit(
            f"expected CPython {EXPECTED_PYTHON}, got {sys.version_info[:3]}"
        )
    if unicodedata.unidata_version != EXPECTED_UNICODE:
        raise SystemExit(
            f"expected Unicode {EXPECTED_UNICODE}, got {unicodedata.unidata_version}"
        )

    lines = [
        "// @generated by tools/references/cpython/unicode_names.py. "
        "Do not edit manually.",
        f"// Regenerate with: {REGENERATION_COMMAND}",
        "pub(crate) static ALIASES: &[(&str, u32)] = &[",
    ]
    for alias, value in aliases():
        quoted = json.dumps(alias)
        entry = f"    ({quoted}, 0x{value:x}),"
        if len(entry) <= 64:
            lines.append(entry)
        else:
            lines.extend(["    (", f"        {quoted},", f"        0x{value:x},", "    ),"])
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", type=Path)
    mode.add_argument("--write", type=Path)
    args = parser.parse_args()
    generated = generate()
    if args.write is not None:
        args.write.write_text(generated, encoding="utf-8")
        return
    current = args.check.read_text(encoding="utf-8")
    if current != generated:
        raise SystemExit(f"{args.check} is stale; run `{REGENERATION_COMMAND}`")


if __name__ == "__main__":
    main()
