// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:python:update
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_mut)]
#[repr(C, align(64))]
#[derive(zerocopy::FromBytes, zerocopy::Immutable)]
struct GeneratedTables {
    states: [u32; 4638usize],
    state_data: [u16; 8661usize],
    goto: [u16; 3025usize],
    token_states: [rezel_lr::TokenState; 100usize],
    token_accepts: [rezel_lr::TokenAccept; 175usize],
    token_edges: [rezel_lr::TokenEdge; 713usize],
    token_eof: [rezel_lr::TokenEof; 0usize],
    dynamic_precedences: [rezel_lr::DynamicPrecedence; 1usize],
}
#[cfg(target_endian = "little")]
static TABLES_LE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.le.bin"
);
#[cfg(target_endian = "big")]
static TABLES_BE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.be.bin"
);
#[cfg(target_endian = "little")]
use TABLES_LE as TABLES;
#[cfg(target_endian = "big")]
use TABLES_BE as TABLES;
static TOKEN_TABLE: rezel_lr::TokenTable = rezel_lr::TokenTable::new(
    &TABLES.token_states,
    &TABLES.token_accepts,
    &TABLES.token_edges,
    &TABLES.token_eof,
);
fn specialize_0(
    value: &str,
    _stack: &rezel_lr::Stack,
) -> Option<rezel_lr::SpecializedToken> {
    match value {
        "False" => {
            Some(rezel_lr::SpecializedToken::new(83u16, rezel_lr::Specialize::Replace))
        }
        "None" => {
            Some(rezel_lr::SpecializedToken::new(82u16, rezel_lr::Specialize::Replace))
        }
        "True" => {
            Some(rezel_lr::SpecializedToken::new(83u16, rezel_lr::Specialize::Replace))
        }
        "and" => {
            Some(rezel_lr::SpecializedToken::new(27u16, rezel_lr::Specialize::Replace))
        }
        "as" => {
            Some(rezel_lr::SpecializedToken::new(104u16, rezel_lr::Specialize::Replace))
        }
        "assert" => {
            Some(rezel_lr::SpecializedToken::new(109u16, rezel_lr::Specialize::Replace))
        }
        "async" => {
            Some(rezel_lr::SpecializedToken::new(50u16, rezel_lr::Specialize::Replace))
        }
        "await" => {
            Some(rezel_lr::SpecializedToken::new(21u16, rezel_lr::Specialize::Replace))
        }
        "break" => {
            Some(rezel_lr::SpecializedToken::new(94u16, rezel_lr::Specialize::Replace))
        }
        "case" => {
            Some(rezel_lr::SpecializedToken::new(145u16, rezel_lr::Specialize::Extend))
        }
        "class" => {
            Some(rezel_lr::SpecializedToken::new(137u16, rezel_lr::Specialize::Replace))
        }
        "continue" => {
            Some(rezel_lr::SpecializedToken::new(96u16, rezel_lr::Specialize::Replace))
        }
        "def" => {
            Some(rezel_lr::SpecializedToken::new(132u16, rezel_lr::Specialize::Replace))
        }
        "del" => {
            Some(rezel_lr::SpecializedToken::new(90u16, rezel_lr::Specialize::Replace))
        }
        "elif" => {
            Some(rezel_lr::SpecializedToken::new(121u16, rezel_lr::Specialize::Replace))
        }
        "else" => {
            Some(rezel_lr::SpecializedToken::new(35u16, rezel_lr::Specialize::Replace))
        }
        "except" => {
            Some(rezel_lr::SpecializedToken::new(127u16, rezel_lr::Specialize::Replace))
        }
        "finally" => {
            Some(rezel_lr::SpecializedToken::new(128u16, rezel_lr::Specialize::Replace))
        }
        "for" => {
            Some(rezel_lr::SpecializedToken::new(51u16, rezel_lr::Specialize::Replace))
        }
        "from" => {
            Some(rezel_lr::SpecializedToken::new(47u16, rezel_lr::Specialize::Replace))
        }
        "global" => {
            Some(rezel_lr::SpecializedToken::new(106u16, rezel_lr::Specialize::Replace))
        }
        "if" => {
            Some(rezel_lr::SpecializedToken::new(34u16, rezel_lr::Specialize::Replace))
        }
        "import" => {
            Some(rezel_lr::SpecializedToken::new(103u16, rezel_lr::Specialize::Replace))
        }
        "in" => {
            Some(rezel_lr::SpecializedToken::new(29u16, rezel_lr::Specialize::Replace))
        }
        "is" => {
            Some(rezel_lr::SpecializedToken::new(31u16, rezel_lr::Specialize::Replace))
        }
        "lambda" => {
            Some(rezel_lr::SpecializedToken::new(37u16, rezel_lr::Specialize::Replace))
        }
        "match" => {
            Some(rezel_lr::SpecializedToken::new(142u16, rezel_lr::Specialize::Extend))
        }
        "nonlocal" => {
            Some(rezel_lr::SpecializedToken::new(107u16, rezel_lr::Specialize::Replace))
        }
        "not" => {
            Some(rezel_lr::SpecializedToken::new(30u16, rezel_lr::Specialize::Replace))
        }
        "or" => {
            Some(rezel_lr::SpecializedToken::new(26u16, rezel_lr::Specialize::Replace))
        }
        "pass" => {
            Some(rezel_lr::SpecializedToken::new(92u16, rezel_lr::Specialize::Replace))
        }
        "raise" => {
            Some(rezel_lr::SpecializedToken::new(101u16, rezel_lr::Specialize::Replace))
        }
        "return" => {
            Some(rezel_lr::SpecializedToken::new(98u16, rezel_lr::Specialize::Replace))
        }
        "try" => {
            Some(rezel_lr::SpecializedToken::new(126u16, rezel_lr::Specialize::Replace))
        }
        "type" => {
            Some(rezel_lr::SpecializedToken::new(111u16, rezel_lr::Specialize::Extend))
        }
        "while" => {
            Some(rezel_lr::SpecializedToken::new(123u16, rezel_lr::Specialize::Replace))
        }
        "with" => {
            Some(rezel_lr::SpecializedToken::new(130u16, rezel_lr::Specialize::Replace))
        }
        "yield" => {
            Some(rezel_lr::SpecializedToken::new(46u16, rezel_lr::Specialize::Replace))
        }
        _ => None,
    }
}
fn node_set() -> &'static std::sync::Arc<rezel_common::NodeSet> {
    static NODE_SET: std::sync::OnceLock<std::sync::Arc<rezel_common::NodeSet>> = std::sync::OnceLock::new();
    NODE_SET
        .get_or_init(|| {
            let mut nodes = Vec::new();
            {
                let mut node = rezel_common::NodeType::new(
                    0u16,
                    "⚠",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ERROR,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    1u16,
                    "Escape",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    2u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    3u16,
                    "Comment",
                    rezel_common::NodeFlags::SKIPPED,
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    4u16,
                    "Module",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    5u16,
                    "AssignStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    6u16,
                    "*",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    7u16,
                    "BinaryExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    8u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    9u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    10u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    11u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    12u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    13u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    14u16,
                    "@",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    15u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    16u16,
                    "**",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    17u16,
                    "UnaryExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    18u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    19u16,
                    "BitOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    20u16,
                    "AwaitExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    21u16,
                    "await",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    22u16,
                    ")",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("(")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    23u16,
                    "(",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize(")")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    24u16,
                    "ParenthesizedExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    25u16,
                    "BinaryExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    26u16,
                    "or",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    27u16,
                    "and",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    28u16,
                    "CompareOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    29u16,
                    "in",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    30u16,
                    "not",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    31u16,
                    "is",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    32u16,
                    "UnaryExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    33u16,
                    "ConditionalExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    34u16,
                    "if",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    35u16,
                    "else",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    36u16,
                    "LambdaExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    37u16,
                    "lambda",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    38u16,
                    "ParamList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    39u16,
                    "VariableName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    40u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    41u16,
                    ",",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    42u16,
                    ":",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    43u16,
                    "NamedExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    44u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    45u16,
                    "YieldExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    46u16,
                    "yield",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    47u16,
                    "from",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    48u16,
                    "TupleExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    49u16,
                    "ComprehensionExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    50u16,
                    "async",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    51u16,
                    "for",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    52u16,
                    "LambdaExpression",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    53u16,
                    "]",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("[")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    54u16,
                    "[",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("]")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    55u16,
                    "ArrayExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    56u16,
                    "ArrayComprehensionExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    57u16,
                    "}",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("{")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    58u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("}")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    59u16,
                    "DictionaryExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    60u16,
                    "DictionaryComprehensionExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    61u16,
                    "SetExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    62u16,
                    "SetComprehensionExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    63u16,
                    "CallExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    64u16,
                    "ArgList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    65u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    66u16,
                    "MemberExpression",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    67u16,
                    ".",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    68u16,
                    "PropertyName",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    69u16,
                    "Number",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    70u16,
                    "String",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    71u16,
                    "FormatString",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    72u16,
                    "FormatReplacement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    73u16,
                    "FormatSelfDoc",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    74u16,
                    "FormatConversion",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    75u16,
                    "FormatSpec",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    76u16,
                    "FormatReplacement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    77u16,
                    "FormatSelfDoc",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    78u16,
                    "TemplateString",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    79u16,
                    "TemplateInterpolation",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    80u16,
                    "ContinuedString",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    81u16,
                    "Ellipsis",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    82u16,
                    "None",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    83u16,
                    "Boolean",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("ExpressionNode")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    84u16,
                    "TypeDef",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    85u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    86u16,
                    "UpdateStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    87u16,
                    "UpdateOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    88u16,
                    "ExpressionStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    89u16,
                    "DeleteStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    90u16,
                    "del",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    91u16,
                    "PassStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    92u16,
                    "pass",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    93u16,
                    "BreakStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    94u16,
                    "break",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    95u16,
                    "ContinueStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    96u16,
                    "continue",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    97u16,
                    "ReturnStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    98u16,
                    "return",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    99u16,
                    "YieldStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    100u16,
                    "RaiseStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    101u16,
                    "raise",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    102u16,
                    "ImportStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    103u16,
                    "import",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    104u16,
                    "as",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    105u16,
                    "ScopeStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    106u16,
                    "global",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    107u16,
                    "nonlocal",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    108u16,
                    "AssertStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    109u16,
                    "assert",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    110u16,
                    "TypeDefinition",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    111u16,
                    "type",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    112u16,
                    "TypeParamList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    113u16,
                    "TypeParam",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    114u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    115u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    116u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    117u16,
                    "StatementGroup",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    118u16,
                    ";",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    119u16,
                    "IfStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    120u16,
                    "Body",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    121u16,
                    "elif",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    122u16,
                    "WhileStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    123u16,
                    "while",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    124u16,
                    "ForStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    125u16,
                    "TryStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    126u16,
                    "try",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    127u16,
                    "except",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    128u16,
                    "finally",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    129u16,
                    "WithStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    130u16,
                    "with",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    131u16,
                    "FunctionDefinition",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    132u16,
                    "def",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    133u16,
                    "ParamList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    134u16,
                    "AssignOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    135u16,
                    "TypeDef",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    136u16,
                    "ClassDefinition",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    137u16,
                    "class",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    138u16,
                    "DecoratedStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    139u16,
                    "Decorator",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    140u16,
                    "At",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    141u16,
                    "MatchStatement",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Statement")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    142u16,
                    "match",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    143u16,
                    "MatchBody",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    144u16,
                    "MatchClause",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    145u16,
                    "case",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    146u16,
                    "CapturePattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    147u16,
                    "LiteralPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    148u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    149u16,
                    "ArithOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    150u16,
                    "AsPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    151u16,
                    "OrPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    152u16,
                    "LogicOp",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    153u16,
                    "AttributePattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    154u16,
                    "SequencePattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    155u16,
                    "MappingPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    156u16,
                    "StarPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    157u16,
                    "ClassPattern",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::group_prop();
                let value = property
                    .deserialize("Pattern")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    158u16,
                    "PatternArgList",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    159u16,
                    "KeywordPattern",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    160u16,
                    "KeywordPattern",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    161u16,
                    "Guard",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    162u16,
                    "Expression",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    163u16,
                    "Interactive",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    164u16,
                    "FunctionType",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    165u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    166u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    167u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    168u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    169u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    170u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    171u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    172u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    173u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    174u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    175u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    176u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    177u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    178u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    179u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    180u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    181u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    182u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    183u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    184u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    185u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    186u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    187u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    188u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    189u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    190u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    191u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    192u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    193u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    194u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    195u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    196u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    197u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    198u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    199u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    200u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    201u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    202u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            std::sync::Arc::new(
                rezel_common::NodeSet::new(nodes).extend(&[crate::python_highlighting()]),
            )
        })
}
static TOKENIZERS: &[rezel_lr::Tokenizer] = &[
    rezel_lr::Tokenizer::External(&crate::tokens::INDENTATION),
    rezel_lr::Tokenizer::External(&crate::tokens::NEWLINES),
    rezel_lr::Tokenizer::External(&crate::tokens::STRINGS),
    rezel_lr::Tokenizer::External(&crate::identifier::TOKENIZER),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(0u8)),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(1u8)),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(2u8)),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(3u8)),
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(4u8)),
];
static TOP_RULES: &[rezel_lr::TopRule] = &[
    rezel_lr::TopRule {
        name: "Module",
        state: 0u16,
        term: 4u16,
    },
    rezel_lr::TopRule {
        name: "Expression",
        state: 1u16,
        term: 162u16,
    },
    rezel_lr::TopRule {
        name: "Interactive",
        state: 2u16,
        term: 163u16,
    },
    rezel_lr::TopRule {
        name: "FunctionType",
        state: 3u16,
        term: 164u16,
    },
];
static DIALECTS: &[rezel_lr::DialectSpec] = &[];
static SPECIALIZERS: &[rezel_lr::SpecializerSpec] = &[
    rezel_lr::SpecializerSpec {
        term: 212u16,
        get: specialize_0,
    },
];
static TERM_NAMES: &[(u16, &str)] = &[
    (0u16, "⚠"),
    (1u16, "Escape"),
    (2u16, "replacementStart"),
    (3u16, "Comment"),
    (4u16, "@top"),
    (5u16, "AssignStatement"),
    (6u16, "\"*\""),
    (7u16, "BinaryExpression"),
    (8u16, "BitOp"),
    (9u16, "BitOp-1"),
    (10u16, "BitOp-2"),
    (11u16, "BitOp-3"),
    (12u16, "ArithOp"),
    (13u16, "ArithOp-1"),
    (14u16, "\"@\""),
    (15u16, "ArithOp-2"),
    (16u16, "\"**\""),
    (17u16, "UnaryExpression"),
    (18u16, "ArithOp-3"),
    (19u16, "BitOp-4"),
    (20u16, "AwaitExpression"),
    (21u16, "identifier/\"await\""),
    (22u16, "\")\""),
    (23u16, "\"(\""),
    (24u16, "ParenthesizedExpression"),
    (25u16, "binaryTest"),
    (26u16, "identifier/\"or\""),
    (27u16, "identifier/\"and\""),
    (28u16, "CompareOp"),
    (29u16, "identifier/\"in\""),
    (30u16, "identifier/\"not\""),
    (31u16, "identifier/\"is\""),
    (32u16, "unaryTest"),
    (33u16, "ConditionalExpression"),
    (34u16, "identifier/\"if\""),
    (35u16, "identifier/\"else\""),
    (36u16, "LambdaExpression"),
    (37u16, "identifier/\"lambda\""),
    (38u16, "lambdaParams"),
    (39u16, "VariableName"),
    (40u16, "AssignOp"),
    (41u16, "\",\""),
    (42u16, "\":\""),
    (43u16, "NamedExpression"),
    (44u16, "AssignOp-1"),
    (45u16, "YieldExpression"),
    (46u16, "identifier/\"yield\""),
    (47u16, "identifier/\"from\""),
    (48u16, "TupleExpression"),
    (49u16, "ComprehensionExpression"),
    (50u16, "identifier/\"async\""),
    (51u16, "identifier/\"for\""),
    (52u16, "LambdaExpression-1"),
    (53u16, "\"]\""),
    (54u16, "\"[\""),
    (55u16, "ArrayExpression"),
    (56u16, "ArrayComprehensionExpression"),
    (57u16, "\"}\""),
    (58u16, "\"{\""),
    (59u16, "DictionaryExpression"),
    (60u16, "DictionaryComprehensionExpression"),
    (61u16, "SetExpression"),
    (62u16, "SetComprehensionExpression"),
    (63u16, "CallExpression"),
    (64u16, "ArgList"),
    (65u16, "AssignOp-2"),
    (66u16, "MemberExpression"),
    (67u16, "\".\""),
    (68u16, "PropertyName"),
    (69u16, "Number"),
    (70u16, "String"),
    (71u16, "FormatString"),
    (72u16, "FormatReplacement"),
    (73u16, "FormatSelfDoc"),
    (74u16, "FormatConversion"),
    (75u16, "FormatSpec"),
    (76u16, "nestedFormatReplacement"),
    (77u16, "FormatSelfDoc-1"),
    (78u16, "TemplateString"),
    (79u16, "TemplateInterpolation"),
    (80u16, "ContinuedString"),
    (81u16, "\"...\""),
    (82u16, "identifier/\"None\""),
    (83u16, "identifier/\"True\""),
    (84u16, "TypeDef"),
    (85u16, "AssignOp-3"),
    (86u16, "UpdateStatement"),
    (87u16, "UpdateOp"),
    (88u16, "ExpressionStatement"),
    (89u16, "DeleteStatement"),
    (90u16, "identifier/\"del\""),
    (91u16, "PassStatement"),
    (92u16, "identifier/\"pass\""),
    (93u16, "BreakStatement"),
    (94u16, "identifier/\"break\""),
    (95u16, "ContinueStatement"),
    (96u16, "identifier/\"continue\""),
    (97u16, "ReturnStatement"),
    (98u16, "identifier/\"return\""),
    (99u16, "YieldStatement"),
    (100u16, "RaiseStatement"),
    (101u16, "identifier/\"raise\""),
    (102u16, "ImportStatement"),
    (103u16, "identifier/\"import\""),
    (104u16, "identifier/\"as\""),
    (105u16, "ScopeStatement"),
    (106u16, "identifier/\"global\""),
    (107u16, "identifier/\"nonlocal\""),
    (108u16, "AssertStatement"),
    (109u16, "identifier/\"assert\""),
    (110u16, "TypeDefinition"),
    (111u16, "identifier/\"type\""),
    (112u16, "TypeParamList"),
    (113u16, "TypeParam"),
    (114u16, "AssignOp-4"),
    (115u16, "AssignOp-5"),
    (116u16, "AssignOp-6"),
    (117u16, "StatementGroup"),
    (118u16, "\";\""),
    (119u16, "IfStatement"),
    (120u16, "Body"),
    (121u16, "identifier/\"elif\""),
    (122u16, "WhileStatement"),
    (123u16, "identifier/\"while\""),
    (124u16, "ForStatement"),
    (125u16, "TryStatement"),
    (126u16, "identifier/\"try\""),
    (127u16, "identifier/\"except\""),
    (128u16, "identifier/\"finally\""),
    (129u16, "WithStatement"),
    (130u16, "identifier/\"with\""),
    (131u16, "FunctionDefinition"),
    (132u16, "identifier/\"def\""),
    (133u16, "ParamList"),
    (134u16, "AssignOp-7"),
    (135u16, "TypeDef-1"),
    (136u16, "ClassDefinition"),
    (137u16, "identifier/\"class\""),
    (138u16, "DecoratedStatement"),
    (139u16, "Decorator"),
    (140u16, "At"),
    (141u16, "MatchStatement"),
    (142u16, "identifier/\"match\""),
    (143u16, "MatchBody"),
    (144u16, "MatchClause"),
    (145u16, "identifier/\"case\""),
    (146u16, "CapturePattern"),
    (147u16, "LiteralPattern"),
    (148u16, "ArithOp-4"),
    (149u16, "ArithOp-5"),
    (150u16, "AsPattern"),
    (151u16, "OrPattern"),
    (152u16, "LogicOp"),
    (153u16, "AttributePattern"),
    (154u16, "SequencePattern"),
    (155u16, "MappingPattern"),
    (156u16, "StarPattern"),
    (157u16, "ClassPattern"),
    (158u16, "PatternArgList"),
    (159u16, "KeywordPattern"),
    (160u16, "KeywordPattern-1"),
    (161u16, "Guard"),
    (162u16, "@top"),
    (163u16, "@top"),
    (164u16, "@top"),
    (165u16, "statement+"),
    (166u16, "\",\" lambdaParam+"),
    (167u16, "\",\" test | \"*\" expression+"),
    (168u16, "\",\" testNamed | \"*\" expression+"),
    (169u16, "\",\" \"*\"? expression+"),
    (170u16, "\",\" test \":\" test | \"**\" expression+"),
    (171u16, "\",\" argument+"),
    (
        172u16,
        "\",\" testNamed | \"*\" expression | testNamed? \":\" testNamed? \":\" testNamed??+",
    ),
    (173u16, "stringContent | Escape+"),
    (174u16, "stringContent | Escape | FormatReplacement+"),
    (175u16, "\",\" \"*\"? test+"),
    (176u16, "formatStringSpecChars | nestedFormatReplacement+"),
    (177u16, "stringContent | Escape | TemplateInterpolation+"),
    (178u16, "String | FormatString+"),
    (179u16, "TemplateString+"),
    (180u16, "\",\" \"*\" expression | test+"),
    (181u16, "AssignOp YieldExpression | expressions+"),
    (182u16, "\",\" test+"),
    (183u16, "\",\" expression+"),
    (184u16, "\".\" VariableName+"),
    (185u16, "\",\" importedName+"),
    (186u16, "\".\" | \"...\"+"),
    (187u16, "\",\" VariableName+"),
    (188u16, "\",\" TypeParam+"),
    (189u16, "\";\" smallStatement?+"),
    (190u16, "kw<\"elif\"> testNamed? Body+"),
    (191u16, "regularExceptClause+"),
    (192u16, "exceptionGroupClause+"),
    (193u16, "\",\" withItem+"),
    (194u16, "\",\" param+"),
    (195u16, "Decorator+"),
    (196u16, "MatchClause+"),
    (197u16, "LogicOp pattern+"),
    (198u16, "\".\" PropertyName+"),
    (199u16, "\",\" \"**\" pattern | VariableName | LiteralPattern \":\" pattern+"),
    (200u16, "\",\" pattern | KeywordPattern+"),
    (201u16, "\",\" pattern+"),
    (202u16, "\",\" test | \"*\" test | \"**\" test+"),
    (203u16, "␄"),
    (204u16, "indent"),
    (205u16, "dedent"),
    (206u16, "newline"),
    (207u16, "blankLineStart"),
    (208u16, "newlineBracketed"),
    (209u16, "eof"),
    (210u16, "stringContent"),
    (211u16, "stringEnd"),
    (212u16, "identifier"),
    (213u16, "%mainskip-1"),
    (214u16, "space"),
    (215u16, "blankLine-1"),
    (216u16, "statement-1"),
    (217u16, "simpleStatement-1"),
    (218u16, "smallStatement-1"),
    (219u16, "commaSep<\"*\" expression | test>-1"),
    (220u16, "expression-1"),
    (221u16, "\"|\""),
    (222u16, "\"^\""),
    (223u16, "\"&\""),
    (224u16, "\"<<\""),
    (225u16, "\">>\""),
    (226u16, "\"+\""),
    (227u16, "\"-\""),
    (228u16, "\"/\""),
    (229u16, "\"%\""),
    (230u16, "\"//\""),
    (231u16, "\"~\""),
    (232u16, "testNamed-1"),
    (233u16, "test-1"),
    (234u16, "testInner-1"),
    (235u16, "lambdaParam-1"),
    (236u16, "\"=\""),
    (237u16, "\":=\""),
    (238u16, "yield-1"),
    (239u16, "commaSep<test | \"*\" expression>-1"),
    (240u16, "compFor-1"),
    (241u16, "commaSep<\"*\"? expression>-1"),
    (242u16, "compIf-1"),
    (243u16, "testNoCond-1"),
    (244u16, "commaSep<testNamed | \"*\" expression>-1"),
    (245u16, "commaSep<test \":\" test | \"**\" expression>-1"),
    (246u16, "commaSep<argument>-1"),
    (247u16, "argument-1"),
    (248u16, "subscript-1"),
    (
        249u16,
        "commaSep<testNamed | \"*\" expression | testNamed? \":\" testNamed? \":\" testNamed??>-1",
    ),
    (250u16, "word"),
    (251u16, "stringStart"),
    (252u16, "stringStartD"),
    (253u16, "stringStartL"),
    (254u16, "stringStartLD"),
    (255u16, "stringStartR"),
    (256u16, "stringStartRD"),
    (257u16, "stringStartRL"),
    (258u16, "stringStartRLD"),
    (259u16, "stringStartF"),
    (260u16, "stringStartFD"),
    (261u16, "stringStartFL"),
    (262u16, "stringStartFLD"),
    (263u16, "stringStartFR"),
    (264u16, "stringStartFRD"),
    (265u16, "stringStartFRL"),
    (266u16, "stringStartFRLD"),
    (267u16, "formatReplacement<replacementStart>-1"),
    (268u16, "commaSep<\"*\"? test>-1"),
    (269u16, "formatStringSpec-1"),
    (270u16, "formatStringSpecChars"),
    (271u16, "formatReplacement<\"{\">-1"),
    (272u16, "stringStartT"),
    (273u16, "stringStartTD"),
    (274u16, "stringStartTL"),
    (275u16, "stringStartTLD"),
    (276u16, "stringStartTR"),
    (277u16, "stringStartTRD"),
    (278u16, "stringStartTRL"),
    (279u16, "stringStartTRLD"),
    (280u16, "commaSep<test>-1"),
    (281u16, "commaSep<expression>-1"),
    (282u16, "importList-1"),
    (283u16, "commaSep<importedName>-1"),
    (284u16, "importedName-1"),
    (285u16, "dottedName-1"),
    (286u16, "importedNames-1"),
    (287u16, "commaSep<VariableName>-1"),
    (288u16, "commaSep<TypeParam>-1"),
    (289u16, "compoundStatement-1"),
    (290u16, "regularExceptClause-1"),
    (291u16, "exceptionGroupClause-1"),
    (292u16, "commaSep<withItem>-1"),
    (293u16, "withItem-1"),
    (294u16, "parenthesizedWithItems-1"),
    (295u16, "commaSep<param>-1"),
    (296u16, "param-1"),
    (297u16, "\"->\""),
    (298u16, "commaSep<pattern>-1"),
    (299u16, "pattern-1"),
    (300u16, "commaSep<\"**\" pattern | VariableName | LiteralPattern \":\" pattern>-1"),
    (301u16, "commaSep<pattern | KeywordPattern>-1"),
    (302u16, "commaSep<test | \"*\" test | \"**\" test>-1"),
];
pub static LANGUAGE: rezel_lr::Language = rezel_lr::Language {
    states: &TABLES.states,
    state_data: &TABLES.state_data,
    goto: &TABLES.goto,
    token_table: &TOKEN_TABLE,
    tokenizers: TOKENIZERS,
    top_rules: TOP_RULES,
    max_term: 302u16,
    min_repeat_term: 165u16,
    token_precedence: 8636usize,
    node_set,
    context: Some(&crate::tokens::TRACK_INDENT),
    dialects: DIALECTS,
    dynamic_precedences: &TABLES.dynamic_precedences,
    specializers: SPECIALIZERS,
    term_names: TERM_NAMES,
};
