// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:json:update
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_mut)]
static STATES: &[u32] = &[
    0, 7, 2, 1, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 2, 0, 589846, 589846, 0, 0, 2, 0, 589830,
    589830, 0, 30, 2, 1, 0, 589833, 0, 38, 2, 1, 0, 589840, 0, 0, 2, 0, 589835, 589835,
    0, 0, 2, 0, 1114121, 1114121, 0, 45, 2, 1, 0, 1114121, 0, 50, 2, 1, 0, 589848, 0, 58,
    2, 1, 0, 589834, 0, 63, 2, 1, 0, 589849, 0, 0, 2, 0, 1114128, 1114128, 0, 71, 2, 1,
    0, 1114128, 0, 0, 2, 0, 1638409, 1638409, 0, 76, 2, 1, 0, 1114136, 0, 33, 2, 1, 0,
    589841, 0, 7, 2, 1, 0, 1114122, 0, 7, 2, 1, 0, 589842, 0, 84, 2, 1, 0, 1114137, 0, 0,
    2, 0, 1638416, 1638416, 0, 0, 2, 0, 1245201, 1245201, 0, 0, 2, 0, 1114129, 1114129,
    0, 0, 2, 0, 1638410, 1638410, 0, 0, 2, 0, 1114130, 1114130, 0, 0, 2, 0, 1245202,
    1245202,
];
static STATE_DATA: &[u16] = &[
    65535, 0, 21, 0, 4, 65535, 0, 2, 2, 0, 3, 2, 0, 4, 2, 0, 5, 2, 0, 8, 4, 0, 15, 5, 0,
    23, 3, 0, 65535, 0, 7, 7, 0, 23, 6, 0, 65535, 0, 14, 12, 0, 65535, 1, 7, 0, 7, 14, 0,
    65535, 0, 13, 16, 0, 7, 24, 9, 65535, 0, 12, 17, 0, 65535, 0, 13, 18, 0, 14, 25, 9,
    65535, 0, 14, 20, 0, 65535, 0, 13, 16, 0, 7, 24, 17, 65535, 0, 13, 18, 0, 14, 25, 17,
    65535, 0,
];
static GOTO: &[u16] = &[
    26, 1, 1, 1, 1, 1, 1, 27, 1, 1, 27, 33, 39, 1, 1, 1, 1, 27, 43, 49, 1, 1, 1, 55, 1,
    67, 70, 9, 2, 0, 5, 17, 18, 2, 9, 4, 3, 22, 16, 5, 10, 4, 16, 2, 15, 9, 3, 21, 15, 2,
    19, 11, 3, 25, 19, 2, 1, 0, 2, 11, 5, 2, 23, 17, 3, 24, 18, 3, 8, 4, 3, 13, 5,
];
static TOKEN_STATES: &[rezel_lr::TokenState] = &[
    rezel_lr::TokenState::new(65535, 0, 0, 0, 17),
    rezel_lr::TokenState::new(65535, 0, 17, 1, 0),
    rezel_lr::TokenState::new(65535, 1, 17, 0, 6),
    rezel_lr::TokenState::new(65535, 1, 23, 1, 0),
    rezel_lr::TokenState::new(65535, 2, 23, 0, 9),
    rezel_lr::TokenState::new(65535, 2, 32, 0, 3),
    rezel_lr::TokenState::new(65535, 2, 35, 0, 3),
    rezel_lr::TokenState::new(65535, 2, 38, 0, 3),
    rezel_lr::TokenState::new(65535, 2, 41, 0, 3),
    rezel_lr::TokenState::new(65535, 2, 44, 1, 0),
    rezel_lr::TokenState::new(65535, 3, 44, 0, 2),
    rezel_lr::TokenState::new(65535, 3, 46, 1, 3),
    rezel_lr::TokenState::new(65535, 4, 49, 0, 1),
    rezel_lr::TokenState::new(65535, 4, 50, 1, 3),
    rezel_lr::TokenState::new(65535, 5, 53, 0, 3),
    rezel_lr::TokenState::new(65535, 5, 56, 0, 1),
    rezel_lr::TokenState::new(65535, 5, 57, 1, 1),
    rezel_lr::TokenState::new(65535, 6, 58, 1, 4),
    rezel_lr::TokenState::new(65535, 7, 62, 1, 0),
    rezel_lr::TokenState::new(65535, 8, 62, 1, 0),
    rezel_lr::TokenState::new(65535, 9, 62, 1, 0),
    rezel_lr::TokenState::new(65535, 10, 62, 0, 1),
    rezel_lr::TokenState::new(65535, 10, 63, 0, 1),
    rezel_lr::TokenState::new(65535, 10, 64, 0, 1),
    rezel_lr::TokenState::new(65535, 10, 65, 0, 1),
    rezel_lr::TokenState::new(65535, 10, 66, 1, 0),
    rezel_lr::TokenState::new(65535, 11, 66, 0, 1),
    rezel_lr::TokenState::new(65535, 11, 67, 0, 1),
    rezel_lr::TokenState::new(65535, 11, 68, 0, 1),
    rezel_lr::TokenState::new(65535, 11, 69, 1, 0),
    rezel_lr::TokenState::new(65535, 12, 69, 0, 1),
    rezel_lr::TokenState::new(65535, 12, 70, 0, 1),
    rezel_lr::TokenState::new(65535, 12, 71, 0, 1),
    rezel_lr::TokenState::new(65535, 12, 72, 1, 0),
    rezel_lr::TokenState::new(65535, 13, 72, 1, 0),
    rezel_lr::TokenState::new(65535, 14, 72, 1, 0),
];
static TOKEN_ACCEPTS: &[rezel_lr::TokenAccept] = &[
    rezel_lr::TokenAccept::new(21, 65535),
    rezel_lr::TokenAccept::new(23, 65535),
    rezel_lr::TokenAccept::new(13, 65535),
    rezel_lr::TokenAccept::new(5, 65535),
    rezel_lr::TokenAccept::new(5, 65535),
    rezel_lr::TokenAccept::new(5, 65535),
    rezel_lr::TokenAccept::new(5, 65535),
    rezel_lr::TokenAccept::new(12, 65535),
    rezel_lr::TokenAccept::new(15, 65535),
    rezel_lr::TokenAccept::new(14, 65535),
    rezel_lr::TokenAccept::new(3, 65535),
    rezel_lr::TokenAccept::new(4, 65535),
    rezel_lr::TokenAccept::new(2, 65535),
    rezel_lr::TokenAccept::new(8, 65535),
    rezel_lr::TokenAccept::new(7, 65535),
];
static TOKEN_EDGES: &[rezel_lr::TokenEdge] = &[
    rezel_lr::TokenEdge::new(9, 10, 1),
    rezel_lr::TokenEdge::new(10, 11, 1),
    rezel_lr::TokenEdge::new(13, 14, 1),
    rezel_lr::TokenEdge::new(32, 33, 1),
    rezel_lr::TokenEdge::new(34, 35, 2),
    rezel_lr::TokenEdge::new(44, 45, 9),
    rezel_lr::TokenEdge::new(45, 46, 10),
    rezel_lr::TokenEdge::new(48, 49, 11),
    rezel_lr::TokenEdge::new(49, 58, 17),
    rezel_lr::TokenEdge::new(58, 59, 18),
    rezel_lr::TokenEdge::new(91, 92, 19),
    rezel_lr::TokenEdge::new(93, 94, 20),
    rezel_lr::TokenEdge::new(102, 103, 21),
    rezel_lr::TokenEdge::new(110, 111, 26),
    rezel_lr::TokenEdge::new(116, 117, 30),
    rezel_lr::TokenEdge::new(123, 124, 34),
    rezel_lr::TokenEdge::new(125, 126, 35),
    rezel_lr::TokenEdge::new(32, 33, 2),
    rezel_lr::TokenEdge::new(33, 34, 2),
    rezel_lr::TokenEdge::new(34, 35, 3),
    rezel_lr::TokenEdge::new(35, 92, 2),
    rezel_lr::TokenEdge::new(92, 93, 4),
    rezel_lr::TokenEdge::new(93, 1114112, 2),
    rezel_lr::TokenEdge::new(34, 35, 2),
    rezel_lr::TokenEdge::new(47, 48, 2),
    rezel_lr::TokenEdge::new(92, 93, 2),
    rezel_lr::TokenEdge::new(98, 99, 2),
    rezel_lr::TokenEdge::new(102, 103, 2),
    rezel_lr::TokenEdge::new(110, 111, 2),
    rezel_lr::TokenEdge::new(114, 115, 2),
    rezel_lr::TokenEdge::new(116, 117, 2),
    rezel_lr::TokenEdge::new(117, 118, 5),
    rezel_lr::TokenEdge::new(48, 58, 6),
    rezel_lr::TokenEdge::new(65, 71, 6),
    rezel_lr::TokenEdge::new(97, 103, 6),
    rezel_lr::TokenEdge::new(48, 58, 7),
    rezel_lr::TokenEdge::new(65, 71, 7),
    rezel_lr::TokenEdge::new(97, 103, 7),
    rezel_lr::TokenEdge::new(48, 58, 8),
    rezel_lr::TokenEdge::new(65, 71, 8),
    rezel_lr::TokenEdge::new(97, 103, 8),
    rezel_lr::TokenEdge::new(48, 58, 2),
    rezel_lr::TokenEdge::new(65, 71, 2),
    rezel_lr::TokenEdge::new(97, 103, 2),
    rezel_lr::TokenEdge::new(48, 49, 11),
    rezel_lr::TokenEdge::new(49, 58, 17),
    rezel_lr::TokenEdge::new(46, 47, 12),
    rezel_lr::TokenEdge::new(69, 70, 14),
    rezel_lr::TokenEdge::new(101, 102, 14),
    rezel_lr::TokenEdge::new(48, 58, 13),
    rezel_lr::TokenEdge::new(48, 58, 13),
    rezel_lr::TokenEdge::new(69, 70, 14),
    rezel_lr::TokenEdge::new(101, 102, 14),
    rezel_lr::TokenEdge::new(43, 44, 15),
    rezel_lr::TokenEdge::new(45, 46, 15),
    rezel_lr::TokenEdge::new(48, 58, 16),
    rezel_lr::TokenEdge::new(48, 58, 16),
    rezel_lr::TokenEdge::new(48, 58, 16),
    rezel_lr::TokenEdge::new(46, 47, 12),
    rezel_lr::TokenEdge::new(48, 58, 17),
    rezel_lr::TokenEdge::new(69, 70, 14),
    rezel_lr::TokenEdge::new(101, 102, 14),
    rezel_lr::TokenEdge::new(97, 98, 22),
    rezel_lr::TokenEdge::new(108, 109, 23),
    rezel_lr::TokenEdge::new(115, 116, 24),
    rezel_lr::TokenEdge::new(101, 102, 25),
    rezel_lr::TokenEdge::new(117, 118, 27),
    rezel_lr::TokenEdge::new(108, 109, 28),
    rezel_lr::TokenEdge::new(108, 109, 29),
    rezel_lr::TokenEdge::new(114, 115, 31),
    rezel_lr::TokenEdge::new(117, 118, 32),
    rezel_lr::TokenEdge::new(101, 102, 33),
];
static TOKEN_EOF: &[rezel_lr::TokenEof] = &[];
static TOKEN_TABLE: rezel_lr::TokenTable = rezel_lr::TokenTable::new(
    TOKEN_STATES,
    TOKEN_ACCEPTS,
    TOKEN_EDGES,
    TOKEN_EOF,
);
fn node_set() -> &'static std::sync::Arc<rezel_common::NodeSet> {
    static NODE_SET: std::sync::OnceLock<std::sync::Arc<rezel_common::NodeSet>> = std::sync::OnceLock::new();
    NODE_SET
        .get_or_init(|| {
            let mut nodes = Vec::new();
            {
                let mut node = rezel_common::NodeType::new(
                    0u16,
                    "⚠",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ERROR,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    1u16,
                    "JsonText",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    2u16,
                    "True",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    3u16,
                    "False",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    4u16,
                    "Null",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    5u16,
                    "Number",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    6u16,
                    "String",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    7u16,
                    "}",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("{")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    8u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("}")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    9u16,
                    "Object",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    10u16,
                    "Property",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    11u16,
                    "PropertyName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    12u16,
                    ":",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    13u16,
                    ",",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    14u16,
                    "]",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("[")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    15u16,
                    "[",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("]")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    16u16,
                    "Array",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    17u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    18u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            std::sync::Arc::new(
                rezel_common::NodeSet::new(nodes).extend(&[crate::json_highlighting()]),
            )
        })
}
static TOKENIZERS: &[rezel_lr::Tokenizer] = &[
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(0u8)),
];
static TOP_RULES: &[rezel_lr::TopRule] = &[
    rezel_lr::TopRule {
        name: "JsonText",
        state: 0u16,
        term: 1u16,
    },
];
static DIALECTS: &[rezel_lr::DialectSpec] = &[];
static DYNAMIC_PRECEDENCES: &[i16] = &[];
static SPECIALIZERS: &[rezel_lr::SpecializerSpec] = &[];
static TERM_NAMES: &[(u16, &str)] = &[
    (0u16, "⚠"),
    (1u16, "@top"),
    (2u16, "True"),
    (3u16, "False"),
    (4u16, "Null"),
    (5u16, "Number"),
    (6u16, "String"),
    (7u16, "\"}\""),
    (8u16, "\"{\""),
    (9u16, "Object"),
    (10u16, "Property"),
    (11u16, "PropertyName"),
    (12u16, "\":\""),
    (13u16, "\",\""),
    (14u16, "\"]\""),
    (15u16, "\"[\""),
    (16u16, "Array"),
    (17u16, "\",\" Property+"),
    (18u16, "\",\" value+"),
    (19u16, "␄"),
    (20u16, "%mainskip-1"),
    (21u16, "whitespace"),
    (22u16, "value-1"),
    (23u16, "string"),
    (24u16, "list<Property>-1"),
    (25u16, "list<value>-1"),
];
pub static LANGUAGE: rezel_lr::Language = rezel_lr::Language {
    states: STATES,
    state_data: STATE_DATA,
    goto: GOTO,
    token_table: &TOKEN_TABLE,
    tokenizers: TOKENIZERS,
    top_rules: TOP_RULES,
    max_term: 25u16,
    min_repeat_term: 17u16,
    token_precedence: 0usize,
    node_set,
    context: None,
    dialects: DIALECTS,
    dynamic_precedences: DYNAMIC_PRECEDENCES,
    specializers: SPECIALIZERS,
    term_names: TERM_NAMES,
};
