// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:json:update
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_mut)]
#[repr(C, align(4))]
#[derive(zerocopy::FromBytes, zerocopy::Immutable)]
struct GeneratedTables {
    states: [u32; 156usize],
    state_data: [u16; 92usize],
    goto: [u16; 73usize],
    token_states: [rezel_lr::TokenState; 36usize],
    token_accepts: [rezel_lr::TokenAccept; 15usize],
    token_edges: [rezel_lr::TokenEdge; 72usize],
    token_eof: [rezel_lr::TokenEof; 0usize],
    dynamic_precedences: [i16; 0usize],
}
#[cfg(target_endian = "little")]
static TABLES_LE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.le.bin"
);
#[cfg(target_endian = "big")]
static TABLES_BE: GeneratedTables = rezel_lr::__private::include_value!(
    "generated.be.bin"
);
#[cfg(target_endian = "little")]
use TABLES_LE as TABLES;
#[cfg(target_endian = "big")]
use TABLES_BE as TABLES;
static TOKEN_TABLE: rezel_lr::TokenTable = rezel_lr::TokenTable::new(
    &TABLES.token_states,
    &TABLES.token_accepts,
    &TABLES.token_edges,
    &TABLES.token_eof,
);
fn node_set() -> &'static std::sync::Arc<rezel_common::NodeSet> {
    static NODE_SET: std::sync::OnceLock<std::sync::Arc<rezel_common::NodeSet>> = std::sync::OnceLock::new();
    NODE_SET
        .get_or_init(|| {
            let mut nodes = Vec::new();
            {
                let mut node = rezel_common::NodeType::new(
                    0u16,
                    "⚠",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ERROR,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    1u16,
                    "JsonText",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    2u16,
                    "True",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    3u16,
                    "False",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    4u16,
                    "Null",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    5u16,
                    "Number",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    6u16,
                    "String",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    7u16,
                    "}",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("{")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    8u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("}")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    9u16,
                    "Object",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    10u16,
                    "Property",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    11u16,
                    "PropertyName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    12u16,
                    ":",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    13u16,
                    ",",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    14u16,
                    "]",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("[")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    15u16,
                    "[",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("]")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    16u16,
                    "Array",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    17u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    18u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            std::sync::Arc::new(
                rezel_common::NodeSet::new(nodes).extend(&[crate::json_highlighting()]),
            )
        })
}
static TOKENIZERS: &[rezel_lr::Tokenizer] = &[
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(0u8)),
];
static TOP_RULES: &[rezel_lr::TopRule] = &[
    rezel_lr::TopRule {
        name: "JsonText",
        state: 0u16,
        term: 1u16,
    },
];
static DIALECTS: &[rezel_lr::DialectSpec] = &[];
static SPECIALIZERS: &[rezel_lr::SpecializerSpec] = &[];
static TERM_NAMES: &[(u16, &str)] = &[
    (0u16, "⚠"),
    (1u16, "@top"),
    (2u16, "True"),
    (3u16, "False"),
    (4u16, "Null"),
    (5u16, "Number"),
    (6u16, "String"),
    (7u16, "\"}\""),
    (8u16, "\"{\""),
    (9u16, "Object"),
    (10u16, "Property"),
    (11u16, "PropertyName"),
    (12u16, "\":\""),
    (13u16, "\",\""),
    (14u16, "\"]\""),
    (15u16, "\"[\""),
    (16u16, "Array"),
    (17u16, "\",\" Property+"),
    (18u16, "\",\" value+"),
    (19u16, "␄"),
    (20u16, "%mainskip-1"),
    (21u16, "whitespace"),
    (22u16, "value-1"),
    (23u16, "string"),
    (24u16, "list<Property>-1"),
    (25u16, "list<value>-1"),
];
pub static LANGUAGE: rezel_lr::Language = rezel_lr::Language {
    states: &TABLES.states,
    state_data: &TABLES.state_data,
    goto: &TABLES.goto,
    token_table: &TOKEN_TABLE,
    tokenizers: TOKENIZERS,
    top_rules: TOP_RULES,
    max_term: 25u16,
    min_repeat_term: 17u16,
    token_precedence: 0usize,
    node_set,
    context: None,
    dialects: DIALECTS,
    dynamic_precedences: &TABLES.dynamic_precedences,
    specializers: SPECIALIZERS,
    term_names: TERM_NAMES,
};
