// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:json:update
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_mut)]
static STATES: &[u32] = &[
    0, 7, 2, 1, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 2, 0, 589846, 589846, 0, 0, 2, 0, 589830,
    589830, 0, 30, 2, 1, 0, 589833, 0, 38, 2, 1, 0, 589840, 0, 0, 2, 0, 589835, 589835,
    0, 0, 2, 0, 1114121, 1114121, 0, 45, 2, 1, 0, 1114121, 0, 50, 2, 1, 0, 589848, 0, 58,
    2, 1, 0, 589834, 0, 63, 2, 1, 0, 589849, 0, 0, 2, 0, 1114128, 1114128, 0, 71, 2, 1,
    0, 1114128, 0, 0, 2, 0, 1638409, 1638409, 0, 76, 2, 1, 0, 1114136, 0, 33, 2, 1, 0,
    589841, 0, 7, 2, 1, 0, 1114122, 0, 7, 2, 1, 0, 589842, 0, 84, 2, 1, 0, 1114137, 0, 0,
    2, 0, 1638416, 1638416, 0, 0, 2, 0, 1245201, 1245201, 0, 0, 2, 0, 1114129, 1114129,
    0, 0, 2, 0, 1638410, 1638410, 0, 0, 2, 0, 1114130, 1114130, 0, 0, 2, 0, 1245202,
    1245202,
];
static STATE_DATA: &[u16] = &[
    65535, 0, 21, 0, 4, 65535, 0, 2, 2, 0, 3, 2, 0, 4, 2, 0, 5, 2, 0, 8, 4, 0, 15, 5, 0,
    23, 3, 0, 65535, 0, 7, 7, 0, 23, 6, 0, 65535, 0, 14, 12, 0, 65535, 1, 7, 0, 7, 14, 0,
    65535, 0, 13, 16, 0, 7, 24, 9, 65535, 0, 12, 17, 0, 65535, 0, 13, 18, 0, 14, 25, 9,
    65535, 0, 14, 20, 0, 65535, 0, 13, 16, 0, 7, 24, 17, 65535, 0, 13, 18, 0, 14, 25, 17,
    65535, 0,
];
static GOTO: &[u16] = &[
    26, 1, 1, 1, 1, 1, 1, 27, 1, 1, 27, 33, 39, 1, 1, 1, 1, 27, 43, 49, 1, 1, 1, 55, 1,
    67, 70, 9, 2, 0, 5, 17, 18, 2, 9, 4, 3, 22, 16, 5, 10, 4, 16, 2, 15, 9, 3, 21, 15, 2,
    19, 11, 3, 25, 19, 2, 1, 0, 2, 11, 5, 2, 23, 17, 3, 24, 18, 3, 8, 4, 3, 13, 5,
];
static TOKEN_DATA: &[u16] = &[
    65535, 3, 17, 9, 10, 54, 10, 11, 54, 13, 14, 54, 32, 33, 54, 34, 35, 59, 44, 45, 175,
    45, 46, 180, 48, 49, 189, 49, 58, 249, 58, 59, 266, 91, 92, 271, 93, 94, 276, 102,
    103, 281, 110, 111, 310, 116, 117, 333, 123, 124, 356, 125, 126, 361, 65535, 59, 0,
    21, 65535, 65535, 62, 8, 32, 33, 59, 33, 34, 59, 34, 35, 86, 35, 92, 59, 92, 93, 91,
    93, 55296, 59, 55296, 56320, 169, 57344, 0, 59, 65535, 91, 0, 23, 65535, 65535, 94,
    9, 34, 35, 59, 47, 48, 59, 92, 93, 59, 98, 99, 59, 102, 103, 59, 110, 111, 59, 114,
    115, 59, 116, 117, 59, 117, 118, 121, 65535, 124, 3, 48, 58, 133, 65, 71, 133, 97,
    103, 133, 65535, 136, 3, 48, 58, 145, 65, 71, 145, 97, 103, 145, 65535, 148, 3, 48,
    58, 157, 65, 71, 157, 97, 103, 157, 65535, 160, 3, 48, 58, 59, 65, 71, 59, 97, 103,
    59, 65535, 172, 1, 56320, 57344, 59, 65535, 180, 0, 13, 65535, 65535, 183, 2, 48, 49,
    189, 49, 58, 249, 65535, 194, 3, 5, 65535, 46, 47, 203, 69, 70, 223, 101, 102, 223,
    65535, 206, 1, 48, 58, 209, 65535, 214, 3, 5, 65535, 48, 58, 209, 69, 70, 223, 101,
    102, 223, 65535, 226, 3, 43, 44, 235, 45, 46, 235, 48, 58, 241, 65535, 238, 1, 48,
    58, 241, 65535, 246, 1, 5, 65535, 48, 58, 241, 65535, 254, 4, 5, 65535, 46, 47, 203,
    48, 58, 249, 69, 70, 223, 101, 102, 223, 65535, 271, 0, 12, 65535, 65535, 276, 0, 15,
    65535, 65535, 281, 0, 14, 65535, 65535, 284, 1, 97, 98, 287, 65535, 290, 1, 108, 109,
    293, 65535, 296, 1, 115, 116, 299, 65535, 302, 1, 101, 102, 305, 65535, 310, 0, 3,
    65535, 65535, 313, 1, 117, 118, 316, 65535, 319, 1, 108, 109, 322, 65535, 325, 1,
    108, 109, 328, 65535, 333, 0, 4, 65535, 65535, 336, 1, 114, 115, 339, 65535, 342, 1,
    117, 118, 345, 65535, 348, 1, 101, 102, 351, 65535, 356, 0, 2, 65535, 65535, 361, 0,
    8, 65535, 65535, 366, 0, 7, 65535,
];
fn node_set() -> &'static std::sync::Arc<rezel_common::NodeSet> {
    static NODE_SET: std::sync::OnceLock<std::sync::Arc<rezel_common::NodeSet>> = std::sync::OnceLock::new();
    NODE_SET
        .get_or_init(|| {
            let mut nodes = Vec::new();
            {
                let mut node = rezel_common::NodeType::new(
                    0u16,
                    "⚠",
                    rezel_common::NodeFlags::SKIPPED | rezel_common::NodeFlags::ERROR,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    1u16,
                    "JsonText",
                    rezel_common::NodeFlags::TOP,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    2u16,
                    "True",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    3u16,
                    "False",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    4u16,
                    "Null",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    5u16,
                    "Number",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    6u16,
                    "String",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    7u16,
                    "}",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("{")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    8u16,
                    "{",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("}")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    9u16,
                    "Object",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    10u16,
                    "Property",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    11u16,
                    "PropertyName",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::isolate_prop();
                let value = property
                    .deserialize("")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    12u16,
                    ":",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    13u16,
                    ",",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    14u16,
                    "]",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::opened_by_prop();
                let value = property
                    .deserialize("[")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    15u16,
                    "[",
                    rezel_common::NodeFlags::default(),
                );
                let property = rezel_common::closed_by_prop();
                let value = property
                    .deserialize("]")
                    .expect("generated grammar property must deserialize");
                node = node.with_prop(property, value);
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    16u16,
                    "Array",
                    rezel_common::NodeFlags::default(),
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    17u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            {
                let mut node = rezel_common::NodeType::new(
                    18u16,
                    "",
                    rezel_common::NodeFlags::ANONYMOUS,
                );
                nodes.push(node);
            }
            std::sync::Arc::new(
                rezel_common::NodeSet::new(nodes).extend(&[crate::json_highlighting()]),
            )
        })
}
static TOKENIZERS: &[rezel_lr::Tokenizer] = &[
    rezel_lr::Tokenizer::Group(rezel_lr::TokenGroup::new(0u8)),
];
static TOP_RULES: &[rezel_lr::TopRule] = &[
    rezel_lr::TopRule {
        name: "JsonText",
        state: 0u16,
        term: 1u16,
    },
];
static DIALECTS: &[rezel_lr::DialectSpec] = &[];
static DYNAMIC_PRECEDENCES: &[i16] = &[];
static SPECIALIZERS: &[rezel_lr::SpecializerSpec] = &[];
static TERM_NAMES: &[(u16, &str)] = &[
    (0u16, "⚠"),
    (1u16, "@top"),
    (2u16, "True"),
    (3u16, "False"),
    (4u16, "Null"),
    (5u16, "Number"),
    (6u16, "String"),
    (7u16, "\"}\""),
    (8u16, "\"{\""),
    (9u16, "Object"),
    (10u16, "Property"),
    (11u16, "PropertyName"),
    (12u16, "\":\""),
    (13u16, "\",\""),
    (14u16, "\"]\""),
    (15u16, "\"[\""),
    (16u16, "Array"),
    (17u16, "\",\" Property+"),
    (18u16, "\",\" value+"),
    (19u16, "␄"),
    (20u16, "%mainskip-1"),
    (21u16, "whitespace"),
    (22u16, "value-1"),
    (23u16, "string"),
    (24u16, "list<Property>-1"),
    (25u16, "list<value>-1"),
];
pub static LANGUAGE: rezel_lr::Language = rezel_lr::Language {
    states: STATES,
    state_data: STATE_DATA,
    goto: GOTO,
    token_data: TOKEN_DATA,
    tokenizers: TOKENIZERS,
    top_rules: TOP_RULES,
    max_term: 25u16,
    min_repeat_term: 17u16,
    token_precedence: 0usize,
    node_set,
    context: None,
    dialects: DIALECTS,
    dynamic_precedences: DYNAMIC_PRECEDENCES,
    specializers: SPECIALIZERS,
    term_names: TERM_NAMES,
};
