// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:json:update
#![allow(non_upper_case_globals)]
pub const Array: u16 = 16u16;
pub const False: u16 = 3u16;
pub const JsonText: u16 = 1u16;
pub const Null: u16 = 4u16;
pub const Number: u16 = 5u16;
pub const Object: u16 = 9u16;
pub const Property: u16 = 10u16;
pub const PropertyName: u16 = 11u16;
pub const String: u16 = 6u16;
pub const True: u16 = 2u16;
