// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:json:update
#![allow(clippy::all, clippy::pedantic, missing_docs)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum JsonKind {
    Error,
    JsonText,
    True,
    False,
    Null,
    Number,
    String,
    RightBrace,
    LeftBrace,
    Object,
    Property,
    PropertyName,
    Colon,
    Comma,
    RightBracket,
    LeftBracket,
    Array,
}
#[derive(Clone, Copy, Debug)]
pub enum JsonLanguage {}
impl rezel_common::SyntaxLanguage for JsonLanguage {
    type Kind = JsonKind;
    fn kind(node: &rezel_common::SyntaxNode) -> Option<Self::Kind> {
        let node_type = node.node_type();
        let node_set = (crate::generated::LANGUAGE.node_set)();
        let expected = node_set.get(node_type.id())?;
        if !node_type.is(expected) {
            return None;
        }
        let kind = match node_type.id() {
            0u16 => JsonKind::Error,
            1u16 => JsonKind::JsonText,
            2u16 => JsonKind::True,
            3u16 => JsonKind::False,
            4u16 => JsonKind::Null,
            5u16 => JsonKind::Number,
            6u16 => JsonKind::String,
            7u16 => JsonKind::RightBrace,
            8u16 => JsonKind::LeftBrace,
            9u16 => JsonKind::Object,
            10u16 => JsonKind::Property,
            11u16 => JsonKind::PropertyName,
            12u16 => JsonKind::Colon,
            13u16 => JsonKind::Comma,
            14u16 => JsonKind::RightBracket,
            15u16 => JsonKind::LeftBracket,
            16u16 => JsonKind::Array,
            _ => return None,
        };
        Some(kind)
    }
}
#[derive(Clone, Debug)]
pub struct JsonRoot {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonRoot {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::JsonText) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonRoot {
    #[must_use]
    pub fn value(&self) -> Option<JsonValue> {
        self.syntax
            .children()
            .filter_map(|node| {
                <JsonValue as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct JsonObject {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonObject {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::Object) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonObject {
    #[must_use]
    pub fn left_brace_token(&self) -> Option<rezel_common::SyntaxNode> {
        self.syntax
            .children()
            .filter(|node| {
                <JsonLanguage as rezel_common::SyntaxLanguage>::kind(node)
                    == Some(JsonKind::LeftBrace)
            })
            .nth(0)
    }
    #[must_use]
    pub fn properties(&self) -> rezel_common::TypedChildren<JsonProperty> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
    #[must_use]
    pub fn right_brace_token(&self) -> Option<rezel_common::SyntaxNode> {
        self.syntax
            .children()
            .filter(|node| {
                <JsonLanguage as rezel_common::SyntaxLanguage>::kind(node)
                    == Some(JsonKind::RightBrace)
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct JsonArray {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonArray {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::Array) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonArray {
    #[must_use]
    pub fn left_bracket_token(&self) -> Option<rezel_common::SyntaxNode> {
        self.syntax
            .children()
            .filter(|node| {
                <JsonLanguage as rezel_common::SyntaxLanguage>::kind(node)
                    == Some(JsonKind::LeftBracket)
            })
            .nth(0)
    }
    #[must_use]
    pub fn values(&self) -> rezel_common::TypedChildren<JsonValue> {
        rezel_common::TypedChildren::new(self.syntax.children())
    }
    #[must_use]
    pub fn right_bracket_token(&self) -> Option<rezel_common::SyntaxNode> {
        self.syntax
            .children()
            .filter(|node| {
                <JsonLanguage as rezel_common::SyntaxLanguage>::kind(node)
                    == Some(JsonKind::RightBracket)
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct JsonProperty {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonProperty {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::Property) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonProperty {
    #[must_use]
    pub fn name(&self) -> Option<JsonPropertyName> {
        self.syntax
            .children()
            .filter_map(|node| {
                <JsonPropertyName as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
    #[must_use]
    pub fn colon_token(&self) -> Option<rezel_common::SyntaxNode> {
        self.syntax
            .children()
            .filter(|node| {
                <JsonLanguage as rezel_common::SyntaxLanguage>::kind(node)
                    == Some(JsonKind::Colon)
            })
            .nth(0)
    }
    #[must_use]
    pub fn value(&self) -> Option<JsonValue> {
        self.syntax
            .children()
            .filter_map(|node| {
                <JsonValue as rezel_common::TypedNode>::downcast_from(node).ok()
            })
            .nth(0)
    }
}
#[derive(Clone, Debug)]
pub struct JsonPropertyName {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonPropertyName {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::PropertyName) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonPropertyName {}
#[derive(Clone, Debug)]
pub struct JsonString {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonString {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::String) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonString {}
#[derive(Clone, Debug)]
pub struct JsonNumber {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonNumber {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::Number) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonNumber {}
#[derive(Clone, Debug)]
pub struct JsonTrue {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonTrue {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::True) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonTrue {}
#[derive(Clone, Debug)]
pub struct JsonFalse {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonFalse {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::False) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonFalse {}
#[derive(Clone, Debug)]
pub struct JsonNull {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for JsonNull {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(JsonKind::Null) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl JsonNull {}
#[derive(Clone, Debug)]
pub enum JsonBoolean {
    True(JsonTrue),
    False(JsonFalse),
}
impl rezel_common::TypedNode for JsonBoolean {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        match <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node) {
            Some(JsonKind::True) => {
                let typed = <JsonTrue as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::True(typed))
            }
            Some(JsonKind::False) => {
                let typed = <JsonFalse as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::False(typed))
            }
            _ => Err(node),
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        match self {
            Self::True(node) => rezel_common::TypedNode::syntax(node),
            Self::False(node) => rezel_common::TypedNode::syntax(node),
        }
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        match self {
            Self::True(node) => rezel_common::TypedNode::into_syntax(node),
            Self::False(node) => rezel_common::TypedNode::into_syntax(node),
        }
    }
}
#[derive(Clone, Debug)]
pub enum JsonValue {
    True(JsonTrue),
    False(JsonFalse),
    Null(JsonNull),
    Number(JsonNumber),
    String(JsonString),
    Object(JsonObject),
    Array(JsonArray),
}
impl rezel_common::TypedNode for JsonValue {
    type Language = JsonLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        match <JsonLanguage as rezel_common::SyntaxLanguage>::kind(&node) {
            Some(JsonKind::True) => {
                let typed = <JsonTrue as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::True(typed))
            }
            Some(JsonKind::False) => {
                let typed = <JsonFalse as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::False(typed))
            }
            Some(JsonKind::Null) => {
                let typed = <JsonNull as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::Null(typed))
            }
            Some(JsonKind::Number) => {
                let typed = <JsonNumber as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::Number(typed))
            }
            Some(JsonKind::String) => {
                let typed = <JsonString as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::String(typed))
            }
            Some(JsonKind::Object) => {
                let typed = <JsonObject as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::Object(typed))
            }
            Some(JsonKind::Array) => {
                let typed = <JsonArray as rezel_common::TypedNode>::downcast_from(node)
                    .expect("kind was checked before generated downcast");
                Ok(Self::Array(typed))
            }
            _ => Err(node),
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        match self {
            Self::True(node) => rezel_common::TypedNode::syntax(node),
            Self::False(node) => rezel_common::TypedNode::syntax(node),
            Self::Null(node) => rezel_common::TypedNode::syntax(node),
            Self::Number(node) => rezel_common::TypedNode::syntax(node),
            Self::String(node) => rezel_common::TypedNode::syntax(node),
            Self::Object(node) => rezel_common::TypedNode::syntax(node),
            Self::Array(node) => rezel_common::TypedNode::syntax(node),
        }
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        match self {
            Self::True(node) => rezel_common::TypedNode::into_syntax(node),
            Self::False(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Null(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Number(node) => rezel_common::TypedNode::into_syntax(node),
            Self::String(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Object(node) => rezel_common::TypedNode::into_syntax(node),
            Self::Array(node) => rezel_common::TypedNode::into_syntax(node),
        }
    }
}
