@file:OptIn(org.jetbrains.kotlin.K1Deprecation::class)

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import org.jetbrains.kotlin.lexer.KotlinLexer
import org.jetbrains.kotlin.lexer.KtTokens

data class CodePointRange(val start: Int, val end: Int)

val expectedKotlinVersion = "2.4.10"
val expectedStartRangeCount = 610
val expectedPartRangeCount = 651
val expectedDigest = "cdef078f3a09da5203cb3e7fbaf15e2b2e83fad78019142770dcccef5fc7c6be"
val regenerationCommand = "mise run codegen:kotlin-identifiers:update"

val lexer = KotlinLexer()

fun isIdentifier(text: String): Boolean {
    lexer.start(text)
    return lexer.tokenType == KtTokens.IDENTIFIER && lexer.tokenEnd == text.length
}

fun acceptsStart(codePoint: Int): Boolean {
    if (!Character.isValidCodePoint(codePoint) || codePoint in 0xD800..0xDFFF) return false
    return isIdentifier(String(Character.toChars(codePoint)))
}

fun acceptsPart(codePoint: Int): Boolean {
    if (!Character.isValidCodePoint(codePoint) || codePoint in 0xD800..0xDFFF) return false
    return isIdentifier("_a" + String(Character.toChars(codePoint)))
}

fun collect(predicate: (Int) -> Boolean): List<CodePointRange> {
    val ranges = mutableListOf<CodePointRange>()
    var start = -1
    for (codePoint in 0..Character.MAX_CODE_POINT) {
        val accepted = predicate(codePoint)
        if (accepted && start < 0) {
            start = codePoint
        } else if (!accepted && start >= 0) {
            ranges += CodePointRange(start, codePoint - 1)
            start = -1
        }
    }
    if (start >= 0) ranges += CodePointRange(start, Character.MAX_CODE_POINT)
    return ranges
}

fun digest(start: List<CodePointRange>, part: List<CodePointRange>): String {
    val bytes = buildString {
        for (range in start) append(range.start).append(':').append(range.end).append(';')
        append('|')
        for (range in part) append(range.start).append(':').append(range.end).append(';')
    }.toByteArray(StandardCharsets.UTF_8)
    return MessageDigest.getInstance("SHA-256")
        .digest(bytes)
        .joinToString("") { byte -> "%02x".format(byte) }
}

fun appendRanges(output: StringBuilder, name: String, ranges: List<CodePointRange>) {
    output.append("pub(super) static ").append(name).append(": &[(u32, u32)] = &[\n")
    for (range in ranges) {
        output.append("    (0x")
            .append(range.start.toString(16))
            .append(", 0x")
            .append(range.end.toString(16))
            .append("),\n")
    }
    output.append("];\n")
}

fun render(start: List<CodePointRange>, part: List<CodePointRange>): String = buildString {
    append("// @generated by tools/references/kotlin/identifier_tables.main.kts.")
    append(" Do not edit manually.\n")
    append("// Regenerate with: ").append(regenerationCommand).append('\n')
    append("// Kotlin 2.4.10 K1 lexer identifier profile.\n\n")
    append("#[cfg(test)]\npub(super) const KOTLIN_VERSION: &str = \"")
        .append(expectedKotlinVersion)
        .append("\";\n")
    append("#[cfg(test)]\npub(super) const TABLE_SHA256: &str =\n    \"")
        .append(expectedDigest)
        .append("\";\n\n")
    appendRanges(this, "IDENTIFIER_START", start)
    append('\n')
    appendRanges(this, "IDENTIFIER_PART", part)
}

val usage = "usage: identifier_tables.main.kts (--check|--write) OUTPUT.rs"
require(args.size == 2 && args[0] in setOf("--check", "--write")) { usage }
require(KotlinVersion.CURRENT.toString() == expectedKotlinVersion) {
    "Kotlin $expectedKotlinVersion is required, found ${KotlinVersion.CURRENT}"
}

val start = collect(::acceptsStart)
val part = collect(::acceptsPart)
val actualDigest = digest(start, part)
require(start.size == expectedStartRangeCount) {
    "expected $expectedStartRangeCount identifier-start ranges, found ${start.size}"
}
require(part.size == expectedPartRangeCount) {
    "expected $expectedPartRangeCount identifier-part ranges, found ${part.size}"
}
require(actualDigest == expectedDigest) {
    "Kotlin $expectedKotlinVersion identifier digest changed: $actualDigest"
}

val path = Path.of(args[1])
val output = render(start, part)
if (args[0] == "--write") {
    Files.writeString(path, output, StandardCharsets.UTF_8)
} else {
    val checked = Files.readString(path, StandardCharsets.UTF_8)
    require(checked == output) { "$path is not generated from Kotlin $expectedKotlinVersion" }
}
println("verified Kotlin $expectedKotlinVersion identifier tables at $path")
