[package]
name = "rezel-lang-php"
version.workspace = true
authors.workspace = true
categories = ["parser-implementations"]
edition.workspace = true
homepage.workspace = true
include = [
	"/src/**",
	"/Cargo.toml",
	"/README.md",
	"/THIRD_PARTY_NOTICES.md",
	"/LICENSE-APACHE",
	"/LICENSE-MIT",
]
keywords = ["php", "parser", "syntax-tree", "cst"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "PHP 8.5 parser and typed concrete syntax for Rezel"

[features]
default = []
highlight = ["dep:rezel-highlight"]

[dependencies]
rezel-common.workspace = true
rezel-highlight = { workspace = true, optional = true }
rezel-lr.workspace = true
zerocopy.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
