// @generated by rezel-generator. Do not edit manually.
// Regenerate with: mise run codegen:rezel:php:update
#![allow(clippy::all, clippy::pedantic, missing_docs)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PhpKind {
    Error,
    Term1,
    HeredocString,
    PipeOp,
    Term4,
    Name,
    QualifiedName,
    Use,
    Function,
    Const,
    EscapeSequence,
    SetVisibility,
    HaltCompilerTail,
    HaltCompiler,
    Abstract,
    LogicOp,
    Array,
    As,
    Boolean,
    Break,
    Case,
    Catch,
    Class,
    Clone,
    Continue,
    Default,
    Declare,
    Do,
    Echo,
    Else,
    Elseif,
    Enddeclare,
    Endfor,
    Endforeach,
    Endif,
    Endswitch,
    Endwhile,
    Enum,
    Extends,
    Final,
    Finally,
    Fn,
    For,
    Foreach,
    From,
    Global,
    Goto,
    If,
    Implements,
    Include,
    IncludeOnce,
    Insteadof,
    Interface,
    List,
    Match,
    Namespace,
    New,
    Null,
    Print,
    Readonly,
    Require,
    RequireOnce,
    Return,
    Switch,
    Throw,
    Trait,
    Try,
    Unset,
    Var,
    Visibility,
    While,
    Yield,
    LineComment,
    BlockComment,
    TextInterpolation,
    PhpClose,
    Text,
    PhpOpen,
    Template,
    HaltCompilerStatement,
    Term88,
    Term89,
    EmptyStatement,
    Term91,
    Term92,
    Block,
    Term94,
    LabelStatement,
    ExpressionStatement,
    ConditionalExpression,
    MatchExpression,
    ParenthesizedExpression,
    MatchBlock,
    MatchArm,
    Term104,
    Term105,
    AssignmentExpression,
    ArrayExpression,
    ValueList,
    VariadicUnpacking,
    Term111,
    Pair,
    Term113,
    Term114,
    ListExpression,
    SubscriptExpression,
    MemberExpression,
    Term119,
    Term120,
    DynamicVariable,
    Term123,
    VariableName,
    Term125,
    CallExpression,
    ArgList,
    NamedArgument,
    SpreadArgument,
    CastExpression,
    UnionType,
    OptionalType,
    NamedType,
    Term136,
    NamespaceName,
    ParenthesizedType,
    IntersectionType,
    ScopedExpression,
    Term147,
    ClassMemberName,
    DynamicMemberName,
    AssignOp,
    UpdateExpression,
    UpdateOp,
    YieldExpression,
    BinaryExpression,
    BitOp,
    CompareOp,
    ArithOp,
    ConcatOp,
    PipelineExpression,
    IncludeExpression,
    RequireExpression,
    CloneExpression,
    CloneArgumentList,
    UnaryExpression,
    ControlOp,
    PrintIntrinsic,
    FunctionExpression,
    Term179,
    Attributes,
    Attribute,
    Static,
    ParamList,
    Parameter,
    VariadicParameter,
    PropertyParameter,
    PropertyHooks,
    PropertyHook,
    UseList,
    ArrowFunction,
    NewExpression,
    BaseClause,
    ClassInterfaceClause,
    DeclarationList,
    ConstDeclaration,
    VariableDeclarator,
    PropertyDeclaration,
    MethodDeclaration,
    UseDeclaration,
    UseInsteadOfClause,
    UseAsClause,
    EnumCase,
    ShellExpression,
    ThrowExpression,
    Integer,
    Float,
    String,
    Interpolation,
    IfStatement,
    ColonBlock,
    SwitchStatement,
    CaseStatement,
    DefaultStatement,
    WhileStatement,
    DoStatement,
    ForStatement,
    ForSpec,
    SequenceExpression,
    ForeachStatement,
    GotoStatement,
    ContinueStatement,
    BreakStatement,
    ReturnStatement,
    TryStatement,
    CatchDeclarator,
    DeclareStatement,
    EchoStatement,
    UnsetStatement,
    FunctionDefinition,
    ClassDeclaration,
    InterfaceDeclaration,
    TraitDeclaration,
    EnumDeclaration,
    EnumBody,
    NamespaceDefinition,
    NamespaceUseDeclaration,
    UseGroup,
    UseClause,
    GlobalDeclaration,
    FunctionStaticDeclaration,
    Program,
}
#[derive(Clone, Copy, Debug)]
pub enum PhpLanguage {}
impl rezel_common::SyntaxLanguage for PhpLanguage {
    type Kind = PhpKind;
    fn kind(node: &rezel_common::SyntaxNode) -> Option<Self::Kind> {
        let node_type = node.node_type();
        let node_set = (crate::generated::LANGUAGE.node_set)();
        let expected = node_set.get(node_type.id())?;
        if !node_type.is(expected) {
            return None;
        }
        let kind = match node_type.id() {
            0u16 => PhpKind::Error,
            1u16 => PhpKind::Term1,
            87u16 => PhpKind::Term1,
            2u16 => PhpKind::HeredocString,
            3u16 => PhpKind::PipeOp,
            4u16 => PhpKind::Term4,
            109u16 => PhpKind::Term4,
            5u16 => PhpKind::Name,
            96u16 => PhpKind::Name,
            121u16 => PhpKind::Name,
            129u16 => PhpKind::Name,
            138u16 => PhpKind::Name,
            140u16 => PhpKind::Name,
            198u16 => PhpKind::Name,
            6u16 => PhpKind::QualifiedName,
            135u16 => PhpKind::QualifiedName,
            7u16 => PhpKind::Use,
            72u16 => PhpKind::Use,
            8u16 => PhpKind::Function,
            46u16 => PhpKind::Function,
            9u16 => PhpKind::Const,
            24u16 => PhpKind::Const,
            10u16 => PhpKind::EscapeSequence,
            11u16 => PhpKind::SetVisibility,
            12u16 => PhpKind::HaltCompilerTail,
            13u16 => PhpKind::HaltCompiler,
            14u16 => PhpKind::Abstract,
            15u16 => PhpKind::LogicOp,
            53u16 => PhpKind::LogicOp,
            61u16 => PhpKind::LogicOp,
            76u16 => PhpKind::LogicOp,
            99u16 => PhpKind::LogicOp,
            143u16 => PhpKind::LogicOp,
            155u16 => PhpKind::LogicOp,
            156u16 => PhpKind::LogicOp,
            157u16 => PhpKind::LogicOp,
            175u16 => PhpKind::LogicOp,
            16u16 => PhpKind::Array,
            17u16 => PhpKind::As,
            18u16 => PhpKind::Boolean,
            19u16 => PhpKind::Break,
            20u16 => PhpKind::Case,
            21u16 => PhpKind::Catch,
            22u16 => PhpKind::Class,
            23u16 => PhpKind::Clone,
            25u16 => PhpKind::Continue,
            26u16 => PhpKind::Default,
            27u16 => PhpKind::Declare,
            28u16 => PhpKind::Do,
            29u16 => PhpKind::Echo,
            30u16 => PhpKind::Else,
            31u16 => PhpKind::Elseif,
            32u16 => PhpKind::Enddeclare,
            33u16 => PhpKind::Endfor,
            34u16 => PhpKind::Endforeach,
            35u16 => PhpKind::Endif,
            36u16 => PhpKind::Endswitch,
            37u16 => PhpKind::Endwhile,
            38u16 => PhpKind::Enum,
            39u16 => PhpKind::Extends,
            40u16 => PhpKind::Final,
            41u16 => PhpKind::Finally,
            42u16 => PhpKind::Fn,
            43u16 => PhpKind::For,
            44u16 => PhpKind::Foreach,
            45u16 => PhpKind::From,
            47u16 => PhpKind::Global,
            48u16 => PhpKind::Goto,
            49u16 => PhpKind::If,
            50u16 => PhpKind::Implements,
            51u16 => PhpKind::Include,
            52u16 => PhpKind::IncludeOnce,
            54u16 => PhpKind::Insteadof,
            55u16 => PhpKind::Interface,
            56u16 => PhpKind::List,
            57u16 => PhpKind::Match,
            58u16 => PhpKind::Namespace,
            59u16 => PhpKind::New,
            60u16 => PhpKind::Null,
            62u16 => PhpKind::Print,
            63u16 => PhpKind::Readonly,
            64u16 => PhpKind::Require,
            65u16 => PhpKind::RequireOnce,
            66u16 => PhpKind::Return,
            67u16 => PhpKind::Switch,
            68u16 => PhpKind::Throw,
            69u16 => PhpKind::Trait,
            70u16 => PhpKind::Try,
            71u16 => PhpKind::Unset,
            73u16 => PhpKind::Var,
            74u16 => PhpKind::Visibility,
            75u16 => PhpKind::While,
            77u16 => PhpKind::Yield,
            78u16 => PhpKind::LineComment,
            79u16 => PhpKind::BlockComment,
            80u16 => PhpKind::TextInterpolation,
            85u16 => PhpKind::TextInterpolation,
            81u16 => PhpKind::PhpClose,
            82u16 => PhpKind::Text,
            83u16 => PhpKind::PhpOpen,
            84u16 => PhpKind::Template,
            86u16 => PhpKind::HaltCompilerStatement,
            88u16 => PhpKind::Term88,
            89u16 => PhpKind::Term89,
            90u16 => PhpKind::EmptyStatement,
            228u16 => PhpKind::EmptyStatement,
            91u16 => PhpKind::Term91,
            92u16 => PhpKind::Term92,
            93u16 => PhpKind::Block,
            223u16 => PhpKind::Block,
            94u16 => PhpKind::Term94,
            95u16 => PhpKind::LabelStatement,
            97u16 => PhpKind::ExpressionStatement,
            98u16 => PhpKind::ConditionalExpression,
            100u16 => PhpKind::MatchExpression,
            101u16 => PhpKind::ParenthesizedExpression,
            102u16 => PhpKind::MatchBlock,
            103u16 => PhpKind::MatchArm,
            104u16 => PhpKind::Term104,
            105u16 => PhpKind::Term105,
            106u16 => PhpKind::AssignmentExpression,
            107u16 => PhpKind::ArrayExpression,
            108u16 => PhpKind::ValueList,
            116u16 => PhpKind::ValueList,
            110u16 => PhpKind::VariadicUnpacking,
            111u16 => PhpKind::Term111,
            112u16 => PhpKind::Pair,
            235u16 => PhpKind::Pair,
            113u16 => PhpKind::Term113,
            114u16 => PhpKind::Term114,
            115u16 => PhpKind::ListExpression,
            117u16 => PhpKind::SubscriptExpression,
            215u16 => PhpKind::SubscriptExpression,
            118u16 => PhpKind::MemberExpression,
            214u16 => PhpKind::MemberExpression,
            119u16 => PhpKind::Term119,
            120u16 => PhpKind::Term120,
            122u16 => PhpKind::DynamicVariable,
            123u16 => PhpKind::Term123,
            124u16 => PhpKind::VariableName,
            125u16 => PhpKind::Term125,
            126u16 => PhpKind::CallExpression,
            176u16 => PhpKind::CallExpression,
            127u16 => PhpKind::ArgList,
            128u16 => PhpKind::NamedArgument,
            130u16 => PhpKind::SpreadArgument,
            131u16 => PhpKind::CastExpression,
            132u16 => PhpKind::UnionType,
            133u16 => PhpKind::OptionalType,
            145u16 => PhpKind::OptionalType,
            134u16 => PhpKind::NamedType,
            136u16 => PhpKind::Term136,
            137u16 => PhpKind::NamespaceName,
            139u16 => PhpKind::NamespaceName,
            141u16 => PhpKind::ParenthesizedType,
            142u16 => PhpKind::IntersectionType,
            144u16 => PhpKind::IntersectionType,
            146u16 => PhpKind::ScopedExpression,
            147u16 => PhpKind::Term147,
            148u16 => PhpKind::ClassMemberName,
            149u16 => PhpKind::DynamicMemberName,
            150u16 => PhpKind::AssignOp,
            151u16 => PhpKind::UpdateExpression,
            207u16 => PhpKind::UpdateExpression,
            152u16 => PhpKind::UpdateOp,
            153u16 => PhpKind::YieldExpression,
            154u16 => PhpKind::BinaryExpression,
            158u16 => PhpKind::BitOp,
            159u16 => PhpKind::BitOp,
            160u16 => PhpKind::BitOp,
            163u16 => PhpKind::BitOp,
            161u16 => PhpKind::CompareOp,
            162u16 => PhpKind::CompareOp,
            164u16 => PhpKind::ArithOp,
            166u16 => PhpKind::ArithOp,
            167u16 => PhpKind::ArithOp,
            208u16 => PhpKind::ArithOp,
            217u16 => PhpKind::ArithOp,
            165u16 => PhpKind::ConcatOp,
            168u16 => PhpKind::PipelineExpression,
            169u16 => PhpKind::IncludeExpression,
            170u16 => PhpKind::RequireExpression,
            171u16 => PhpKind::CloneExpression,
            172u16 => PhpKind::CloneArgumentList,
            173u16 => PhpKind::UnaryExpression,
            216u16 => PhpKind::UnaryExpression,
            174u16 => PhpKind::ControlOp,
            177u16 => PhpKind::PrintIntrinsic,
            178u16 => PhpKind::FunctionExpression,
            179u16 => PhpKind::Term179,
            180u16 => PhpKind::Attributes,
            181u16 => PhpKind::Attribute,
            182u16 => PhpKind::Static,
            183u16 => PhpKind::ParamList,
            184u16 => PhpKind::Parameter,
            185u16 => PhpKind::VariadicParameter,
            186u16 => PhpKind::PropertyParameter,
            187u16 => PhpKind::PropertyParameter,
            188u16 => PhpKind::PropertyHooks,
            189u16 => PhpKind::PropertyHook,
            190u16 => PhpKind::UseList,
            203u16 => PhpKind::UseList,
            191u16 => PhpKind::ArrowFunction,
            192u16 => PhpKind::NewExpression,
            193u16 => PhpKind::BaseClause,
            194u16 => PhpKind::ClassInterfaceClause,
            195u16 => PhpKind::DeclarationList,
            196u16 => PhpKind::ConstDeclaration,
            245u16 => PhpKind::ConstDeclaration,
            197u16 => PhpKind::VariableDeclarator,
            200u16 => PhpKind::VariableDeclarator,
            246u16 => PhpKind::VariableDeclarator,
            199u16 => PhpKind::PropertyDeclaration,
            201u16 => PhpKind::MethodDeclaration,
            202u16 => PhpKind::UseDeclaration,
            204u16 => PhpKind::UseInsteadOfClause,
            205u16 => PhpKind::UseAsClause,
            206u16 => PhpKind::EnumCase,
            209u16 => PhpKind::ShellExpression,
            210u16 => PhpKind::ThrowExpression,
            211u16 => PhpKind::Integer,
            212u16 => PhpKind::Float,
            213u16 => PhpKind::String,
            219u16 => PhpKind::String,
            218u16 => PhpKind::Interpolation,
            220u16 => PhpKind::IfStatement,
            221u16 => PhpKind::ColonBlock,
            226u16 => PhpKind::ColonBlock,
            222u16 => PhpKind::SwitchStatement,
            224u16 => PhpKind::CaseStatement,
            225u16 => PhpKind::DefaultStatement,
            227u16 => PhpKind::WhileStatement,
            229u16 => PhpKind::DoStatement,
            230u16 => PhpKind::ForStatement,
            231u16 => PhpKind::ForSpec,
            234u16 => PhpKind::ForSpec,
            232u16 => PhpKind::SequenceExpression,
            233u16 => PhpKind::ForeachStatement,
            236u16 => PhpKind::GotoStatement,
            237u16 => PhpKind::ContinueStatement,
            238u16 => PhpKind::BreakStatement,
            239u16 => PhpKind::ReturnStatement,
            240u16 => PhpKind::TryStatement,
            241u16 => PhpKind::CatchDeclarator,
            242u16 => PhpKind::DeclareStatement,
            243u16 => PhpKind::EchoStatement,
            244u16 => PhpKind::UnsetStatement,
            247u16 => PhpKind::FunctionDefinition,
            248u16 => PhpKind::ClassDeclaration,
            249u16 => PhpKind::InterfaceDeclaration,
            250u16 => PhpKind::TraitDeclaration,
            251u16 => PhpKind::EnumDeclaration,
            252u16 => PhpKind::EnumBody,
            253u16 => PhpKind::NamespaceDefinition,
            254u16 => PhpKind::NamespaceUseDeclaration,
            255u16 => PhpKind::UseGroup,
            256u16 => PhpKind::UseClause,
            257u16 => PhpKind::UseClause,
            258u16 => PhpKind::GlobalDeclaration,
            259u16 => PhpKind::FunctionStaticDeclaration,
            260u16 => PhpKind::Program,
            _ => return None,
        };
        Some(kind)
    }
}
#[derive(Clone, Debug)]
pub struct PhpTemplate {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpTemplate {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Template) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpTemplate {}
#[derive(Clone, Debug)]
pub struct PhpProgram {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpProgram {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Program) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpProgram {}
#[derive(Clone, Debug)]
pub struct PhpText {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpText {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Text) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpText {}
#[derive(Clone, Debug)]
pub struct PhpTextInterpolation {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpTextInterpolation {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::TextInterpolation) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpTextInterpolation {}
#[derive(Clone, Debug)]
pub struct PhpName {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpName {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Name) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpName {}
#[derive(Clone, Debug)]
pub struct PhpVariableName {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpVariableName {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::VariableName) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpVariableName {}
#[derive(Clone, Debug)]
pub struct PhpFunctionDefinition {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpFunctionDefinition {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::FunctionDefinition) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpFunctionDefinition {}
#[derive(Clone, Debug)]
pub struct PhpClassDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpClassDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::ClassDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpClassDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpInterfaceDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpInterfaceDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::InterfaceDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpInterfaceDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpTraitDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpTraitDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::TraitDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpTraitDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpEnumDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpEnumDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::EnumDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpEnumDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpPropertyDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpPropertyDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::PropertyDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpPropertyDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpPropertyHook {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpPropertyHook {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::PropertyHook) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpPropertyHook {}
#[derive(Clone, Debug)]
pub struct PhpMethodDeclaration {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpMethodDeclaration {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::MethodDeclaration) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpMethodDeclaration {}
#[derive(Clone, Debug)]
pub struct PhpExpressionStatement {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpExpressionStatement {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::ExpressionStatement) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpExpressionStatement {}
#[derive(Clone, Debug)]
pub struct PhpBinaryExpression {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpBinaryExpression {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::BinaryExpression) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpBinaryExpression {}
#[derive(Clone, Debug)]
pub struct PhpCallExpression {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpCallExpression {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::CallExpression) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpCallExpression {}
#[derive(Clone, Debug)]
pub struct PhpMemberExpression {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpMemberExpression {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::MemberExpression) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpMemberExpression {}
#[derive(Clone, Debug)]
pub struct PhpString {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpString {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::String) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpString {}
#[derive(Clone, Debug)]
pub struct PhpInteger {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpInteger {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Integer) {
            Ok(Self { syntax: node })
        } else {
            Err(node)
        }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpInteger {}
#[derive(Clone, Debug)]
pub struct PhpFloat {
    syntax: rezel_common::SyntaxNode,
}
impl rezel_common::TypedNode for PhpFloat {
    type Language = PhpLanguage;
    fn downcast_from(
        node: rezel_common::SyntaxNode,
    ) -> Result<Self, rezel_common::SyntaxNode> {
        let kind = <PhpLanguage as rezel_common::SyntaxLanguage>::kind(&node);
        if kind == Some(PhpKind::Float) { Ok(Self { syntax: node }) } else { Err(node) }
    }
    fn syntax(&self) -> &rezel_common::SyntaxNode {
        &self.syntax
    }
    fn into_syntax(self) -> rezel_common::SyntaxNode {
        self.syntax
    }
}
impl PhpFloat {}
